# Generated by Django 5.2.11 on 2026-02-11 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Używane w URL, np. 'bialystok'", max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150, verbose_name='Nazwa wyświetlana')),
                ('description', models.TextField(blank=True, null=True)),
                ('country_icon', models.CharField(default='🇵🇱', max_length=10)),
                ('country_name', models.CharField(default='Polska', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_zoom', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)])),
            ],
            options={
                'verbose_name': 'Miasto',
                'verbose_name_plural': 'Miasta',
            },
        ),
        migrations.CreateModel(
            name='GTFSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='np. ZTM Białystok', max_length=100)),
                ('static_url', models.URLField(verbose_name='GTFS Static URL')),
                ('realtime_url', models.URLField(blank=True, null=True, verbose_name='GTFS Realtime URL')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='CzyPrzyjedzieApp.city')),
            ],
        ),
        migrations.CreateModel(
            name='GTFSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_to_all_cities', models.BooleanField(default=False, verbose_name='Działa w każdym mieście')),
                ('additional_cities', models.ManyToManyField(blank=True, related_name='additional_feeds', to='CzyPrzyjedzieApp.city', verbose_name='Dodatkowe miasta')),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='CzyPrzyjedzieApp.gtfsfeed')),
            ],
        ),
    ]
