# Generated by Django 5.2.11 on 2026-02-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CzyPrzyjedzieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsfeed',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=255)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stop_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('route_types', models.JSONField(default=list)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='CzyPrzyjedzieApp.gtfsfeed')),
            ],
            options={
                'verbose_name': 'Przystanek',
                'verbose_name_plural': 'Przystanki',
                'unique_together': {('feed', 'stop_id')},
            },
        ),
    ]
