# Generated by Django 5.2.11 on 2026-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CzyPrzyjedzieApp', '0002_gtfsfeed_last_updated_stop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtfsfeed',
            options={'verbose_name': 'Feed GTFS', 'verbose_name_plural': 'Feedy GTFS'},
        ),
        migrations.AlterModelOptions(
            name='gtfssettings',
            options={'verbose_name': 'Ustawienia GTFS', 'verbose_name_plural': 'Ustawienia GTFS'},
        ),
        migrations.RemoveField(
            model_name='gtfsfeed',
            name='realtime_url',
        ),
        migrations.AddField(
            model_name='gtfsfeed',
            name='service_alerts_url',
            field=models.URLField(blank=True, null=True, verbose_name='GTFS Realtime ServiceAlerts URL'),
        ),
        migrations.AddField(
            model_name='gtfsfeed',
            name='trip_updates_url',
            field=models.URLField(blank=True, null=True, verbose_name='GTFS Realtime TripUpdates URL'),
        ),
        migrations.AddField(
            model_name='gtfsfeed',
            name='vehicle_positions_url',
            field=models.URLField(blank=True, null=True, verbose_name='GTFS Realtime VehiclePositions URL'),
        ),
    ]
