#!/usr/bin/env python3
"""
GTFS-Static + GTFS-Realtime generator for Polish city transit APIs (format: przystanki.*)

Usage:
  python gtfs_combined.py              # Generate all cities, then repeat daily at midnight
  python gtfs_combined.py bialystok    # One-shot generation for a single city

Dependencies:
  pip install aiohttp gtfs-realtime-bindings requests
"""

import argparse
import asyncio
import csv
import io
import json
import logging
import math
import os
import sys
import threading
import time
import zipfile
from collections import defaultdict
from datetime import datetime, timedelta
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any
from zoneinfo import ZoneInfo  # Python 3.9+

import aiohttp
import requests
from aiohttp import web
from google.transit import gtfs_realtime_pb2


# ══════════════════════════════════════════════════════════════════════════════
#  KONFIGURACJA
# ══════════════════════════════════════════════════════════════════════════════

CITIES: list[dict] = [
    {
        "name": "bialystok",
        "base_url": "https://przystanki.bialystok.pl/portal",
        "realtime": True,  # ← ustaw False, by pominąć GTFS-RT dla tego miasta

        # ── Realtime-specific ─────────────────────────────────────────────
        # URL źródłowy pojazdów (CeSIP / traces)
        "cesip_traces_url": "https://przystanki.bialystok.pl/csip/ext_channel/traces.json",
        # Jak często (sekundy) odświeżać pozycje pojazdów
        "realtime_refresh_sec": 10,

        # ── Agencja ───────────────────────────────────────────────────────
        "agency": {
            "agency_id":       "BKM",
            "agency_name":     "Zarząd Białostockiej Komunikacji Miejskiej",
            "agency_url":      "https://komunikacja.bialystok.pl",
            "agency_timezone": "Europe/Warsaw",
            "agency_lang":     "pl",
            "agency_phone":    "+48 85 869 69 69",
            "agency_fare_url": "https://komunikacja.bialystok.pl/",
            "agency_email":    "bkm@um.bialystok.pl",
        },

        # ── Feed info ─────────────────────────────────────────────────────
        "feed_info": {
            "feed_publisher_name": "Unofficial GTFS of Białostocka Komunikacja Miejska, generated by pawlinski07",
            "feed_publisher_url":  "https://github.com/pawlinski07/pawlinski-gtfs",
            "feed_lang":           "pl",
            "feed_timezone":       "Europe/Warsaw",
        },

        # ── Kolory linii (opcjonalne) ─────────────────────────────────────
        "route_colors": [
            {"lines": "1-6",   "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "8-9",   "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "11-21", "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "23-30", "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "50",    "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": ["105", "107", "111"],    "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": ["7", "10", "22"],        "route_color": "225AC9", "route_text_color": "FFFFFF"},
            {"lines": ["200", "201", "202"],    "route_color": "BE080A", "route_text_color": "FFFFFF"},
            {"lines": "100-104",               "route_color": "225AC9", "route_text_color": "FFFFFF"},
            {"lines": "108-109",               "route_color": "225AC9", "route_text_color": "FFFFFF"},
            {"lines": "112-142",               "route_color": "225AC9", "route_text_color": "FFFFFF"},
            {"lines": ["N1","N2","N3","N4","N5","N6"], "route_color": "31285F", "route_text_color": "FFFFFF"},
            {"lines": ["J1","J2","J3","J4","J5","J6"], "route_color": "D83E46", "route_text_color": "FFFFFF"},
        ],

        # ── Scalanie brygad w bloki (opcjonalne) ─────────────────────────
        # Używane zarówno przy generowaniu GTFS-Static (trips.txt → block_id)
        # jak i przy dopasowywaniu pojazdów do kursów w GTFS-RT.
        "block_id_merges": [
            {"service_id": "P", "brigades": ["009-01", "126-01"],                     "block_id": "009-01+126-01"},
            {"service_id": "P", "brigades": ["102-01", "122-01", "132-01"],           "block_id": "102-01+122-01+132-01"},
            {"service_id": "P", "brigades": ["102-02", "122-02", "132-02"],           "block_id": "102-02+122-02+132-02"},
            {"service_id": "P", "brigades": ["102-03", "122-03", "132-03"],           "block_id": "102-03+122-03+132-03"},
            {"service_id": "P", "brigades": ["111-02", "111-03"],                     "block_id": "111-02+111-03"},
            {"service_id": "R", "brigades": ["102-01", "132-01", "132-02", "102-02"], "block_id": "102-01+132-01+132-02+102-02"},
            {"service_id": "R", "brigades": ["108-01", "108-02"],                     "block_id": "108-01+108-02"},
            {"service_id": "R", "brigades": ["111-01", "111-02", "111-03", "111-04"], "block_id": "111-01+111-02+111-03+111-04"},
            {"service_id": "S", "brigades": ["111-01", "111-02"],                     "block_id": "111-01+111-02"},
            {"service_id": "S", "brigades": ["108-01", "108-02"],                     "block_id": "108-01+108-02"},
        ],
    },
]

# ── Współdzielona konfiguracja ────────────────────────────────────────────────

# Maksymalna liczba równoczesnych żądań HTTP (na miasto)
CONCURRENCY: int = 15
# Opóźnienie między żądaniami (grzeczność)
REQUEST_DELAY: float = 0.05
# Ponowne próby przy błędach przejściowych
MAX_RETRIES: int = 3
# Katalog wyjściowy na pliki ZIP i PB
OUTPUT_DIR: str = "gtfs_output"
# Adres i port serwera HTTP
HTTP_HOST: str = "127.0.0.1"
HTTP_PORT: int = 8090
HTTP_PREFIX: str = "/bialystokgtfs"
# Legacy (nie uruchamiamy już osobnego serwera RT na osobnym porcie).
RT_HTTP_PORT: int = 8060
RT_HTTP_PREFIX: str = "/bialystokrealtime"

# Mapowanie typów linii na route_type wg GTFS
ROUTE_TYPE_MAP: dict[str, int] = {
    "BUS":   3,
    "TRAM":  0,
    "METRO": 1,
    "TRAIN": 2,
    "FERRY": 4,
}

# ── Dodatkowe przystanki (wstrzykiwane do stops.txt po generowaniu) ────────────
#
# stop_id i stop_code muszą być unikalne i nie kolidować z danymi z API.
# location_type=0 oznacza zwykły przystanek.
#
# WAŻNE: EXTRA_STOPS są wstrzykiwane do stops.txt DOPIERO PO zakończeniu
# generowania GTFS-Static przez generate_city() – czyli po cleanup'ie
# przystanków bez kursów pobranych z endpointów API.
# Odbywa się to w inject_manual_trips(), wywoływanej zawsze po generate_city().
#
EXTRA_STOPS: list[dict] = [
    {
        "stop_id":       "1000",
        "stop_code":     "1000",
        "stop_name":     "Składowa/Zajezdnia KPK",
        "stop_lat":      53.116355,
        "stop_lon":      23.128103,
        "location_type": 0,
    },
    {
        "stop_id":       "1001",
        "stop_code":     "1001",
        "stop_name":     "Składowa/Zajezdnia KPKM",
        "stop_lat":      53.116149,
        "stop_lon":      23.128144,
        "location_type": 0,
    },
    {
        "stop_id":       "1002",
        "stop_code":     "1002",
        "stop_name":     "Zajezdnia KZK",
        "stop_lat":      53.139029,
        "stop_lon":      23.198122,
        "location_type": 0,
    },
]

# ── Ręcznie dodawane kursy (wyjazdy / zjazdy itp.) ────────────────────────────
#
# Każdy wpis opisuje jeden kurs (trip) dla wybranych typów dni serwisu.
# Pola:
#   route_id       – route_id linii z routes.txt
#   block_id       – block_id przypisany do kursu w trips.txt
#   service_ids    – lista bazowych service_id (np. ["P", "R"]), dla których
#                    kurs ma być dodany; muszą istnieć w calendar_dates.txt
#   trip_headsign  – wyświetlany kierunek (np. "Wyjazd - Centrum Przydworcowe")
#   direction_id   – 0 lub 1 (opcjonalne; domyślnie "")
#   stops          – lista przystanków w kolejności; każdy słownik zawiera:
#       stop_id        – stop_id z stops.txt (może być z EXTRA_STOPS)
#                        UWAGA: stop_id to symbol przystanku (np. "935"),
#                        zgodnie z konwencją używaną w całym feedzie.
#       departure_time – HH:MM:SS (dla ostatniego przystanku = arrival_time)
#       pickup_type    – 0=normalny, 1=brak, 2=telefoniczny, 3=wymagane zgłoszenie
#       drop_off_type  – j.w.
#
# shape jest generowany automatycznie przez OSRM dla każdej unikalnej pary
# przystanków początkowy→końcowy (shape_id = "M_<from_stop>_<to_stop>").
#
# WAŻNE: MANUAL_TRIPS są wstrzykiwane DOPIERO PO cleanup'ie przystanków
# z endpointów API (patrz komentarz przy EXTRA_STOPS).
#
MANUAL_TRIPS: list[dict] = [
    {
        "route_id":     "100",
        "block_id":     "100-06",
        "service_ids":  ["P"],
        "trip_headsign": "Wyjazd - Centrum Przydworcowe",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "05:57:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "881",  "departure_time": "06:14:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "100",
        "block_id":     "100-06",
        "service_ids":  ["P"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "884", "departure_time": "08:55:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "09:02:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },

    {
        "route_id":     "100",
        "block_id":     "100-06",
        "service_ids":  ["P"],
        "trip_headsign": "Wyjazd - Centrum Przydworcowe",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "13:20:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "881",  "departure_time": "13:42:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "100",
        "block_id":     "100-06",
        "service_ids":  ["P"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "884", "departure_time": "18:08:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "18:15:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },


    {
        "route_id":     "100",
        "block_id":     "100-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Centrum Przydworcowe",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "04:04:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "881",  "departure_time": "04:22:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "100",
        "block_id":     "100-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "884", "departure_time": "17:24:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "17:42:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },



    	{
        "route_id":     "N1",
        "block_id":     "N1-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N1",
        "block_id":     "N1-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:05:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "04:14:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N1",
        "block_id":     "N1-02",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N1",
        "block_id":     "N1-02",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:35:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "03:44:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N2",
        "block_id":     "N2-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N2",
        "block_id":     "N2-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "564", "departure_time": "03:43:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:53:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N2",
        "block_id":     "N2-02",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N2",
        "block_id":     "N2-02",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "564", "departure_time": "03:13:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:23:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N3",
        "block_id":     "N3-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N3",
        "block_id":     "N3-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "611", "departure_time": "03:50:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:57:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N3",
        "block_id":     "N3-02",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Transportowa",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:11:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "495",  "departure_time": "00:18:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N3",
        "block_id":     "N3-02",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "611", "departure_time": "03:20:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:30:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N4",
        "block_id":     "N4-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N4",
        "block_id":     "N4-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:06:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "04:15:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N4",
        "block_id":     "N4-02",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N4",
        "block_id":     "N4-02",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:36:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:45:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N5",
        "block_id":     "N5-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N5",
        "block_id":     "N5-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:06:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "04:15:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N5",
        "block_id":     "N5-02",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N5",
        "block_id":     "N5-02",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:36:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "03:45:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N6",
        "block_id":     "N6-01",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N6",
        "block_id":     "N6-01",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:05:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "04:14:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N6",
        "block_id":     "N6-02",
        "service_ids":  ["R"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N6",
        "block_id":     "N6-02",
        "service_ids":  ["R"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:35:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "03:44:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	
		{
        "route_id":     "N1",
        "block_id":     "N1-01",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N1",
        "block_id":     "N1-01",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:05:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "04:14:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N1",
        "block_id":     "N1-02",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N1",
        "block_id":     "N1-02",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:35:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "03:44:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N2",
        "block_id":     "N2-01",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N2",
        "block_id":     "N2-01",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "564", "departure_time": "03:43:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:53:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N2",
        "block_id":     "N2-02",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N2",
        "block_id":     "N2-02",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "564", "departure_time": "03:13:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:23:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N3",
        "block_id":     "N3-01",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N3",
        "block_id":     "N3-01",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "611", "departure_time": "03:50:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:57:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N3",
        "block_id":     "N3-02",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Transportowa",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:11:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "495",  "departure_time": "00:18:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N3",
        "block_id":     "N3-02",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "611", "departure_time": "03:20:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:30:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N4",
        "block_id":     "N4-01",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N4",
        "block_id":     "N4-01",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:06:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "04:15:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N4",
        "block_id":     "N4-02",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1000", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N4",
        "block_id":     "N4-02",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPK",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:36:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1000",  "departure_time": "03:45:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N5",
        "block_id":     "N5-01",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N5",
        "block_id":     "N5-01",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:06:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "04:15:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N5",
        "block_id":     "N5-02",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N5",
        "block_id":     "N5-02",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:36:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "03:45:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	
	
	{
        "route_id":     "N6",
        "block_id":     "N6-01",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:01:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:10:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N6",
        "block_id":     "N6-01",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "04:05:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "04:14:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
	{
        "route_id":     "N6",
        "block_id":     "N6-02",
        "service_ids":  ["S"],
        "trip_headsign": "Wyjazd - Rzeka Biała",
        "direction_id": 0,
        "stops": [
            {"stop_id": "1001", "departure_time": "00:31:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "417",  "departure_time": "00:40:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
    {
        "route_id":     "N6",
        "block_id":     "N6-02",
        "service_ids":  ["S"],
        "trip_headsign": "Zjazd - Zajezdnia KPKM",
        "direction_id": 1,
        "stops": [
            {"stop_id": "417", "departure_time": "03:35:00", "pickup_type": 1, "drop_off_type": 1},
            {"stop_id": "1001",  "departure_time": "03:44:00", "pickup_type": 1, "drop_off_type": 1},
        ],
    },
]

# URL serwera OSRM używanego do generowania shape'ów dla ręcznych kursów.
# Możesz zastąpić lokalną instancją, np. "http://localhost:5000"
OSRM_URL: str = "http://router.project-osrm.org"


# ══════════════════════════════════════════════════════════════════════════════
#  LOGGING
# ══════════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════════
#  FUNKCJE POMOCNICZE (STATYCZNE)
# ══════════════════════════════════════════════════════════════════════════════

_WARSAW = ZoneInfo("Europe/Warsaw")


def secs_to_hhmmss(secs: int) -> str:
    h = secs // 3600
    m = (secs % 3600) // 60
    s = secs % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def _hhmmss_to_secs(t: str) -> int:
    """Konwertuje HH:MM:SS (dopuszczalne H > 23 dla kursów po północy) na sekundy."""
    h, m, s = map(int, t.split(":"))
    return h * 3600 + m * 60 + s


def ms_to_date_str(ms: int) -> str:
    return datetime.fromtimestamp(ms / 1000, tz=_WARSAW).strftime("%Y%m%d")


def strip_today_suffix(symbol: str) -> str:
    idx = symbol.find("_T")
    return symbol[:idx] if idx != -1 else symbol


def write_gtfs_csv(rows: list[dict], fieldnames: list[str]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=fieldnames, lineterminator="\r\n", extrasaction="ignore")
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def build_route_color_lookup(route_colors_cfg: list[dict]) -> dict[str, tuple[str, str]]:
    lookup: dict[str, tuple[str, str]] = {}
    for rule in route_colors_cfg:
        color      = rule["route_color"]
        text_color = rule["route_text_color"]
        spec       = rule["lines"]
        if isinstance(spec, list):
            names = [str(n) for n in spec]
        elif isinstance(spec, str) and "-" in spec:
            parts = spec.split("-", 1)
            if parts[0].isdigit() and parts[1].isdigit():
                names = [str(i) for i in range(int(parts[0]), int(parts[1]) + 1)]
            else:
                names = [spec]
        else:
            names = [str(spec)]
        for name in names:
            lookup[name] = (color, text_color)
    return lookup


def build_block_id_lookup(block_id_merges: list[dict]) -> dict[tuple[str, str], str]:
    lookup: dict[tuple[str, str], str] = {}
    for rule in block_id_merges:
        sid      = rule["service_id"]
        block_id = rule["block_id"]
        for brigade in rule["brigades"]:
            lookup[(sid, brigade)] = block_id
    return lookup


# ══════════════════════════════════════════════════════════════════════════════
#  KLIENT HTTP (asynchroniczny, dla generatora statycznego)
# ══════════════════════════════════════════════════════════════════════════════

class APIClient:
    def __init__(self, base_url: str, session: aiohttp.ClientSession, semaphore: asyncio.Semaphore) -> None:
        self.base    = base_url.rstrip("/")
        self.session = session
        self.sem     = semaphore

    async def get(self, path: str, params: dict | None = None) -> Any | None:
        url = f"{self.base}/{path}"
        async with self.sem:
            await asyncio.sleep(REQUEST_DELAY)
            for attempt in range(MAX_RETRIES):
                try:
                    async with self.session.get(
                        url, params=params, ssl=False,
                        timeout=aiohttp.ClientTimeout(total=30),
                    ) as resp:
                        resp.raise_for_status()
                        return await resp.json(content_type=None)
                except Exception as exc:
                    if attempt == MAX_RETRIES - 1:
                        log.warning("Request failed after %d attempts: %s %s - %s", MAX_RETRIES, url, params, exc)
                        return None
                    await asyncio.sleep(2 ** attempt)
        return None


# ══════════════════════════════════════════════════════════════════════════════
#  GENERATOR GTFS-STATIC
# ══════════════════════════════════════════════════════════════════════════════

async def generate_city(city_cfg: dict) -> bytes:
    """
    Pobiera dane API dla jednego miasta i zwraca GTFS ZIP jako bajty.

    Zwrócony ZIP zawiera WYŁĄCZNIE dane z endpointów API – bez EXTRA_STOPS
    i MANUAL_TRIPS. Ich wstrzyknięcie jest celowo odroczone do inject_manual_trips(),
    która musi być wywołana na wyniku tej funkcji. Dzięki temu cleanup
    nieużywanych przystanków (filtr used_stop_ids) obejmuje tylko dane z API
    i nie jest zanieczyszczony ręcznie dodanymi pozycjami.
    """

    city_name  = city_cfg["name"]
    base_url   = city_cfg["base_url"]
    agency_cfg = city_cfg["agency"]
    feed_cfg   = city_cfg["feed_info"]

    route_color_lookup = build_route_color_lookup(city_cfg.get("route_colors") or [])
    block_id_lookup    = build_block_id_lookup(city_cfg.get("block_id_merges") or [])
    use_route_colors   = bool(route_color_lookup)

    now          = datetime.now()
    feed_start   = now.strftime("%Y%m%d")
    feed_end     = (now + timedelta(days=90)).strftime("%Y%m%d")
    feed_version = now.strftime("%Y%m%d%H%M")

    log.info("[%s] Rozpoczynanie generowania GTFS-Static ...", city_name)

    sem       = asyncio.Semaphore(CONCURRENCY)
    connector = aiohttp.TCPConnector(limit=CONCURRENCY)

    async with aiohttp.ClientSession(connector=connector) as session:
        api = APIClient(base_url, session, sem)

        # 1. Zasoby bazowe
        log.info("[%s] Pobieranie danych bazowych (przystanki, linie, kalendarz, warianty) ...", city_name)
        stops_data, lines_data, calendar_data, variant_names_raw, main_variants_raw = await asyncio.gather(
            api.get("getStops.json"),
            api.get("getLines.json"),
            api.get("getCalendar.json"),
            api.get("getMappedVariantNames.json"),
            api.get("getMainVariantsByLineName.json"),
        )

        stops         = stops_data["stopPoints"]
        lines         = lines_data["lines"]
        calendar_days = calendar_data["days"]
        variant_names = variant_names_raw or {}

        variant_direction: dict[int, int] = {}
        for _line, variants in (main_variants_raw or {}).items():
            if isinstance(variants, list):
                if len(variants) > 1 and variants[1] is not None:
                    variant_direction[int(variants[1])] = 0
                if len(variants) > 2 and variants[2] is not None:
                    variant_direction[int(variants[2])] = 1

        log.info("[%s] direction_id: %d wariantów zmapowanych", city_name, len(variant_direction))

        # stop_id = symbol przystanku (string) – spójne z całym feedem GTFS.
        # Klucz słownika to symbol (używany w zapytaniach atomowych),
        # wartość – pełny obiekt przystanku z API.
        symbol_to_stop:  dict[str, dict] = {s["symbol"]: s for s in stops}
        line_name_to_id: dict[str, int]  = {l["name"]: l["name"] for l in lines}

        log.info("[%s] %d przystanków, %d linii, %d dni kalendarza",
                 city_name, len(stops), len(lines), len(calendar_days))

        # 2. Kalendarz → service_id
        service_dates: dict[str, list[str]]    = defaultdict(list)
        service_representative: dict[str, int] = {}

        for day in calendar_days:
            raw_sym    = day["dayType"]["dayTypeSymbol"]
            service_id = strip_today_suffix(raw_sym)
            date_str   = ms_to_date_str(day["date"])
            service_dates[service_id].append(date_str)
            if "_T" not in raw_sym and service_id not in service_representative:
                service_representative[service_id] = day["date"]

        for day in calendar_days:
            raw_sym    = day["dayType"]["dayTypeSymbol"]
            service_id = strip_today_suffix(raw_sym)
            if service_id not in service_representative:
                service_representative[service_id] = day["date"]

        log.info("[%s] %d typy serwisu: %s",
                 city_name, len(service_representative), list(service_representative.keys()))

        # 3. Rozkłady atomowe
        total_calls = len(stops) * len(service_representative)
        log.info("[%s] Pobieranie rozkładów atomowych (%d przystanków x %d typów = %d zapytań) ...",
                 city_name, len(stops), len(service_representative), total_calls)

        async def fetch_atomic(stop_symbol: str, date_ms: int, service_id: str):
            data = await api.get("getAtomicSchedule.json", {"symbol": stop_symbol, "date": date_ms})
            return stop_symbol, service_id, data

        atomic_tasks = [
            fetch_atomic(s["symbol"], date_ms, sid)
            for sid, date_ms in service_representative.items()
            for s in stops
        ]

        trips_meta:     dict[int, dict]     = {}
        seen_orders:    dict[int, set]      = defaultdict(set)
        stop_times_raw: dict[int, list]     = defaultdict(list)

        completed      = 0
        atomic_results = await asyncio.gather(*atomic_tasks, return_exceptions=True)

        for result in atomic_results:
            completed += 1
            if completed % 500 == 0 or completed == total_calls:
                log.info("[%s] Przetworzono %d / %d odpowiedzi atomowych",
                         city_name, completed, total_calls)

            if isinstance(result, Exception) or result is None:
                continue

            stop_symbol, service_id, data = result
            if data is None or "lineSchedules" not in data:
                continue

            stop = symbol_to_stop.get(stop_symbol)
            if stop is None:
                continue

            # stop_id = symbol przystanku (string), spójny z getStops.json
            stop_id     = stop["symbol"]
            on_request  = bool(stop.get("onRequest"))
            getting_out = bool(stop.get("gettingOut"))

            if on_request:
                pickup_type, dropoff_type = 3, 3
            elif getting_out:
                pickup_type, dropoff_type = 1, 0
            else:
                pickup_type, dropoff_type = 0, 0

            for line_name, line_sched in data["lineSchedules"].items():
                route_id = line_name_to_id.get(line_name, line_name)
                for dep in line_sched["departures"]:
                    course_id  = dep["courseId"]
                    order      = dep["orderInCourse"]
                    variant_id = dep["variantId"]
                    brigade    = dep.get("brigade") or ""

                    if course_id not in trips_meta:
                        headsign = (
                            dep.get("optionalDirection")
                            or variant_names.get(str(variant_id), "")
                        )
                        trips_meta[course_id] = {
                            "trip_id":       course_id,
                            "route_id":      route_id,
                            "service_id":    service_id,
                            "shape_id":      variant_id,
                            "trip_headsign": headsign,
                            "variant_id":    variant_id,
                            "brigade":       brigade,
                        }

                    if order not in seen_orders[course_id]:
                        seen_orders[course_id].add(order)
                        stop_times_raw[course_id].append((
                            order, stop_id, dep["scheduledDepartureSec"],
                            pickup_type, dropoff_type,
                        ))

        log.info("[%s] Zebrano %d kursów, %d wpisów stop_times",
                 city_name, len(trips_meta),
                 sum(len(v) for v in stop_times_raw.values()))

        # 4. Shapes + nagłówki wariantów
        variant_ids = sorted({t["variant_id"] for t in trips_meta.values()})
        log.info("[%s] Pobieranie %d kształtów wariantów ...", city_name, len(variant_ids))

        shape_tasks   = [api.get("getTheoreticalCourseDetails.json", {"variantId": vid}) for vid in variant_ids]
        shape_results = await asyncio.gather(*shape_tasks, return_exceptions=True)

        shapes:           dict[int, list[tuple[float, float]]] = {}
        variant_headsign: dict[int, str]                       = {}

        for vid, res in zip(variant_ids, shape_results):
            if isinstance(res, Exception) or res is None:
                continue
            if "segments" not in res:
                continue
            optional_name = res.get("optionalName") or ""
            if optional_name:
                variant_headsign[vid] = optional_name
            points: list[tuple[float, float]] = []
            for seg in res["segments"]:
                nodes     = sorted(seg["nodes"], key=lambda n: n["orderNo"])
                start_idx = 1 if points else 0
                for node in nodes[start_idx:]:
                    points.append((node["latitude"], node["longitude"]))
            if points:
                shapes[vid] = points

        log.info("[%s] Kształty: %d / %d wariantów; %d nagłówków",
                 city_name, len(shapes), len(variant_ids), len(variant_headsign))

        # 4b. Uzupełnienie trip_headsign i direction_id
        for trip in trips_meta.values():
            vid = trip["variant_id"]
            if not trip["trip_headsign"]:
                trip["trip_headsign"] = variant_headsign.get(vid, "")
            trip["direction_id"] = variant_direction.get(vid, "")

        # 4c. Brakujące końcowe przystanki przez getRealCourse
        log.info("[%s] Pobieranie getRealCourse dla %d kursów ...", city_name, len(trips_meta))

        # Mapowanie symbol → symbol (stop_id = symbol w całym feedzie)
        symbol_to_stop_id: dict[str, str] = {s["symbol"]: s["symbol"] for s in stops}

        real_course_tasks   = [api.get("getRealCourse.json", {"courseId": cid}) for cid in trips_meta]
        real_course_results = await asyncio.gather(*real_course_tasks, return_exceptions=True)

        patched = 0
        for course_id, result in zip(trips_meta.keys(), real_course_results):
            if isinstance(result, Exception) or result is None:
                continue
            real_course = result.get("realCourse")
            if not real_course:
                continue
            for stopping in (real_course.get("stoppings") or []):
                order    = stopping["orderInCourse"]
                symbol   = stopping["stopPointSymbol"]
                dep_secs = stopping["scheduledDepartureSec"]
                if order in seen_orders[course_id]:
                    continue
                stop_id = symbol_to_stop_id.get(symbol)
                if stop_id is None:
                    log.debug("[%s] getRealCourse: nieznany symbol %s (kurs %s)", city_name, symbol, course_id)
                    continue
                seen_orders[course_id].add(order)
                stop_times_raw[course_id].append((order, stop_id, dep_secs, 0, 0))
                patched += 1

        log.info("[%s] Uzupełniono %d wpisów stop_times z getRealCourse", city_name, patched)

    # ── 5. Budowanie plików CSV ───────────────────────────────────────────────

    # agency.txt
    agency_fields_ordered = [
        "agency_id", "agency_name", "agency_url", "agency_timezone",
        "agency_lang", "agency_phone", "agency_fare_url", "agency_email",
    ]
    agency_present = [f for f in agency_fields_ordered if f in agency_cfg]
    agency_csv     = write_gtfs_csv([agency_cfg], agency_present)

    # stops.txt – tylko przystanki z endpointów API, które mają przynajmniej
    # jeden stop_time. Cleanup dotyczy wyłącznie danych z API – EXTRA_STOPS
    # (ręcznie dodane przystanki) są wstrzykiwane później przez inject_manual_trips().
    used_stop_ids: set[str] = {
        entry[1]
        for entries in stop_times_raw.values()
        for entry in entries
    }
    stops_rows = [
        {
            # stop_id = symbol przystanku (string) – klucz używany w stop_times.txt
            "stop_id":       s["symbol"],
            "stop_code":     s["symbol"],
            "stop_name":     s["name"],
            "stop_lat":      s["latitude"],
            "stop_lon":      s["longitude"],
            "location_type": 0,
        }
        for s in stops
        if s["symbol"] in used_stop_ids
    ]
    removed_stops = len(stops) - len(stops_rows)
    if removed_stops:
        log.info("[%s] stops.txt: usunięto %d przystanków bez stop_times", city_name, removed_stops)
    stops_csv = write_gtfs_csv(
        stops_rows,
        ["stop_id", "stop_code", "stop_name", "stop_lat", "stop_lon", "location_type"],
    )

    # routes.txt
    route_fields = ["route_id", "agency_id", "route_short_name", "route_long_name", "route_type"]
    if use_route_colors:
        route_fields += ["route_color", "route_text_color"]

    seen_route_ids: set = set()
    routes_rows = []
    for line in lines:
        if line["id"] in seen_route_ids:
            continue
        seen_route_ids.add(line["id"])
        row: dict = {
            "route_id":         line["name"],
            "agency_id":        agency_cfg["agency_id"],
            "route_short_name": line["name"],
            "route_long_name":  "",
            "route_type":       ROUTE_TYPE_MAP.get(line.get("lineType", "BUS"), 3),
        }
        if use_route_colors:
            color_pair          = route_color_lookup.get(line["name"])
            row["route_color"]      = color_pair[0] if color_pair else ""
            row["route_text_color"] = color_pair[1] if color_pair else ""
        routes_rows.append(row)
    routes_csv = write_gtfs_csv(routes_rows, route_fields)

    # calendar_dates.txt
    cal_rows = [
        {"service_id": sid, "date": date_str, "exception_type": 1}
        for sid, dates in service_dates.items()
        for date_str in dates
    ]
    cal_rows.sort(key=lambda r: (r["date"], r["service_id"]))
    cal_csv = write_gtfs_csv(cal_rows, ["service_id", "date", "exception_type"])

    # trips.txt
    trips_rows = []
    for t in trips_meta.values():
        brigade    = t["brigade"]
        service_id = t["service_id"]
        block_id   = block_id_lookup.get((service_id, brigade), brigade) if brigade else ""
        trips_rows.append({
            "route_id":      t["route_id"],
            "service_id":    service_id,
            "trip_id":       t["trip_id"],
            "trip_headsign": t["trip_headsign"],
            "direction_id":  t.get("direction_id", ""),
            "shape_id":      t["shape_id"],
            "block_id":      block_id,
        })
    trips_csv = write_gtfs_csv(
        trips_rows,
        ["route_id", "service_id", "trip_id", "trip_headsign", "direction_id", "shape_id", "block_id"],
    )

    # stop_times.txt
    _DAY = 86400
    st_rows = []
    for course_id, entries in stop_times_raw.items():
        sorted_entries = sorted(entries)
        offset   = 0
        prev_raw = None
        for order, stop_id, dep_secs, pickup_type, dropoff_type in sorted_entries:
            if prev_raw is not None and dep_secs < prev_raw:
                offset += _DAY
            prev_raw = dep_secs
            time_str = secs_to_hhmmss(dep_secs + offset)
            st_rows.append({
                "trip_id":        course_id,
                "arrival_time":   time_str,
                "departure_time": time_str,
                "stop_id":        stop_id,
                "stop_sequence":  order,
                "pickup_type":    pickup_type,
                "drop_off_type":  dropoff_type,
            })
    st_rows.sort(key=lambda r: (r["trip_id"], r["stop_sequence"]))
    st_csv = write_gtfs_csv(
        st_rows,
        ["trip_id", "arrival_time", "departure_time",
         "stop_id", "stop_sequence", "pickup_type", "drop_off_type"],
    )

    # shapes.txt
    shapes_rows = [
        {"shape_id": sid, "shape_pt_lat": lat, "shape_pt_lon": lon, "shape_pt_sequence": seq}
        for sid, points in shapes.items()
        for seq, (lat, lon) in enumerate(points)
    ]
    shapes_csv = write_gtfs_csv(
        shapes_rows,
        ["shape_id", "shape_pt_lat", "shape_pt_lon", "shape_pt_sequence"],
    )

    # feed_info.txt
    feed_row = {
        "feed_publisher_name": feed_cfg["feed_publisher_name"],
        "feed_publisher_url":  feed_cfg["feed_publisher_url"],
        "feed_lang":           feed_cfg.get("feed_lang", "pl"),
        "feed_timezone":       feed_cfg.get("feed_timezone", "Europe/Warsaw"),
        "feed_start_date":     feed_start,
        "feed_end_date":       feed_end,
        "feed_version":        feed_version,
    }
    feed_csv = write_gtfs_csv([feed_row], list(feed_row.keys()))

    # ── 6. ZIP ───────────────────────────────────────────────────────────────
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("agency.txt",         agency_csv)
        zf.writestr("stops.txt",          stops_csv)
        zf.writestr("routes.txt",         routes_csv)
        zf.writestr("calendar_dates.txt", cal_csv)
        zf.writestr("trips.txt",          trips_csv)
        zf.writestr("stop_times.txt",     st_csv)
        zf.writestr("shapes.txt",         shapes_csv)
        zf.writestr("feed_info.txt",      feed_csv)

    size = buf.tell()
    log.info("[%s] Generowanie ukończone – ZIP: %s bajtów (%.1f MB)",
             city_name, f"{size:,}", size / 1_048_576)
    return buf.getvalue()


# ══════════════════════════════════════════════════════════════════════════════
#  STAN REALTIME (na miasto)
# ══════════════════════════════════════════════════════════════════════════════

class RealtimeState:
    """
    Przechowuje dane GTFS-Static załadowane do pamięci RAM – przystanki,
    stop_times oraz mapę bloków – potrzebne do generowania GTFS-RT.
    Dane bloków są budowane bezpośrednio z trips.txt w ZIP (bez zewnętrznego API).
    Jedna instancja na miasto z włączonym realtime=True.

    Struktura blocks_cache:
        block_id → lista kursów POSORTOWANA wg pierwszego odjazdu rosnąco,
                   każdy kurs: {"trip_id": str, "route_id": str, "first_dep_sec": int}
        Indeks na tej liście (courseBrigadeIndex z traces.json) wskazuje
        konkretny kurs w ramach bloku.
    """

    def __init__(self, city_cfg: dict) -> None:
        self.city_cfg  = city_cfg
        self.city_name = city_cfg["name"]

        # Dane statyczne w RAM
        self.stops:      dict[str, tuple[float, float]] = {}  # stop_id → (lat, lon)
        self.stop_times: dict[str, list[dict]]          = {}  # trip_id → lista

        # Dzisiejszy bazowy service_id (np. "P", "R", "S")
        self.today_service_id: str | None = None

        # Mapa bloków zbudowana z trips.txt + stop_times.txt
        # block_id → [{"trip_id": str, "route_id": str, "first_dep_sec": int}, ...]
        # (posortowana wg first_dep_sec)
        self.blocks_cache: dict[str, list[dict]] = {}

        # Blokada do bezpiecznego odczytu/zapisu między wątkami
        self._lock = threading.Lock()

    # ── Ładowanie wszystkich danych z ZIP ─────────────────────────────────────

    def load_from_zip(self, zip_bytes: bytes) -> None:
        """
        Wczytuje z bajtów ZIP:
          • stops.txt          → self.stops
          • stop_times.txt     → self.stop_times
          • trips.txt          → self.blocks_cache  (przez _build_blocks)
          • calendar_dates.txt → self.today_service_id
        Wszystkie dane są przeładowywane atomowo pod blokadą.
        """
        city_name = self.city_name

        new_stops:      dict[str, tuple[float, float]] = {}
        new_stop_times: dict[str, list[dict]]          = {}
        # trip_id → {route_id, block_id} – potrzebne do zbudowania bloków
        trip_meta:      dict[str, dict]                = {}
        # Zbieramy pierwsze odjazdy per trip_id z stop_times (seq == min)
        # Używamy sekund od północy żeby można było sortować
        trip_first_dep: dict[str, int]                 = {}

        with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:

            # stops.txt
            with zf.open("stops.txt") as f:
                for row in csv.DictReader(io.TextIOWrapper(f, encoding="utf-8")):
                    new_stops[row["stop_id"]] = (
                        float(row["stop_lat"]),
                        float(row["stop_lon"]),
                    )

            # trips.txt → zapamiętujemy route_id, block_id i service_id per trip_id
            with zf.open("trips.txt") as f:
                for row in csv.DictReader(io.TextIOWrapper(f, encoding="utf-8")):
                    trip_meta[row["trip_id"]] = {
                        "route_id":   row["route_id"],
                        "block_id":   row.get("block_id", ""),
                        "service_id": row.get("service_id", ""),
                    }

            # stop_times.txt → budujemy listę przystanków i wyznaczamy
            # czas pierwszego odjazdu (min stop_sequence) per trip_id
            with zf.open("stop_times.txt") as f:
                for row in csv.DictReader(io.TextIOWrapper(f, encoding="utf-8")):
                    tid = row["trip_id"]
                    seq = int(row["stop_sequence"])
                    dep = row["departure_time"]

                    new_stop_times.setdefault(tid, []).append({
                        "stop_id":   row["stop_id"],
                        "arrival":   row["arrival_time"],
                        "departure": dep,
                        "seq":       seq,
                    })

                    # Wyznaczamy czas pierwszego odjazdu (najniższy seq)
                    dep_sec = _hhmmss_to_secs(dep)
                    if tid not in trip_first_dep or seq < new_stop_times[tid][-2]["seq"]:
                        # Aktualizujemy bezpiecznie po sortowaniu poniżej
                        pass  # obsłużone po pętli

            # Sortowanie stop_times i wyznaczenie first_dep_sec
            for tid, stops_list in new_stop_times.items():
                stops_list.sort(key=lambda r: r["seq"])
                trip_first_dep[tid] = _hhmmss_to_secs(stops_list[0]["departure"])

            # calendar_dates.txt → dzisiejszy service_id
            today_str      = datetime.now(tz=_WARSAW).strftime("%Y%m%d")
            new_service_id: str | None = None
            with zf.open("calendar_dates.txt") as f:
                for row in csv.DictReader(io.TextIOWrapper(f, encoding="utf-8")):
                    if row["date"] == today_str and row["exception_type"] == "1":
                        new_service_id = row["service_id"].split("-")[0]
                        break

        # Budowanie blocks_cache z trip_meta i trip_first_dep
        new_blocks = self._build_blocks(
            trip_meta, trip_first_dep, new_service_id,
        )

        with self._lock:
            self.stops            = new_stops
            self.stop_times       = new_stop_times
            self.today_service_id = new_service_id
            self.blocks_cache     = new_blocks

        log.info(
            "[%s] RealtimeState załadowany: %d przystanków, %d kursów, "
            "%d bloków, service_id='%s'",
            city_name, len(new_stops), len(new_stop_times),
            len(new_blocks), new_service_id,
        )

    # ── Budowanie mapy bloków z danych GTFS ──────────────────────────────────

    def _build_blocks(
        self,
        trip_meta:      dict[str, dict],
        trip_first_dep: dict[str, int],
        today_service_id: str | None,
    ) -> dict[str, list[dict]]:
        """
        Buduje słownik block_id → lista kursów posortowana wg czasu
        pierwszego odjazdu.

        Uwzględnia wyłącznie kursy pasujące do dzisiejszego service_id
        (porównanie prefiksu, np. "P" pasuje do "P", "P-0", "P-2").
        Kursy bez block_id lub z pustym block_id są pomijane – nie da się
        ich przypisać do brygady.
        """
        raw: dict[str, list[dict]] = defaultdict(list)

        for tid, meta in trip_meta.items():
            block_id = meta.get("block_id", "").strip()
            if not block_id:
                continue  # kurs bez bloku – nie można dopasować przez indeks

            # Filtrowanie po dzisiejszym service_id (jeśli znany)
            # trip_meta nie zawiera service_id bezpośrednio – musimy go wyciągnąć;
            # jest przechowywany osobno dopiero po wczytaniu calendar_dates.
            # Zamiast tego filtrujemy po prefiksie service_id zawartym w trip_id.
            # trips.txt zawiera kolumnę service_id – wczytujemy go w load_from_zip
            # jako trip_meta["service_id"]. Dodamy go poniżej w load_from_zip.
            trip_service = meta.get("service_id", "")
            if today_service_id is not None:
                base = trip_service.split("-")[0]
                if base != today_service_id:
                    continue

            raw[block_id].append({
                "trip_id":       tid,
                "route_id":      meta["route_id"],
                "first_dep_sec": trip_first_dep.get(tid, 0),
            })

        # Sortowanie kursów w każdym bloku wg czasu pierwszego odjazdu
        result: dict[str, list[dict]] = {}
        for block_id, courses in raw.items():
            result[block_id] = sorted(courses, key=lambda c: c["first_dep_sec"])

        return result

    # ── Rozwiązywanie block_id (scalanie brygad) ──────────────────────────────

    def resolve_block_id(self, brigade: str) -> str:
        """
        Zwraca efektywny block_id uwzględniając reguły scalania brygad
        (BLOCK_ID_MERGES) dla dzisiejszego service_id.
        Jeśli brygada nie należy do żadnej grupy scalania, zwraca ją bez zmian
        – bo w trips.txt block_id == oryginalna brygada dla takich kursów.
        """
        sid = self.today_service_id
        if sid is None:
            return brigade
        for merge in (self.city_cfg.get("block_id_merges") or []):
            if merge["service_id"] == sid and brigade in merge["brigades"]:
                merged = merge["block_id"]
                log.debug("[%s] Brygada '%s' → block_id '%s'", self.city_name, brigade, merged)
                return merged
        return brigade

    # ── Pobieranie kursu po brygadzie i indeksie ─────────────────────────────

    def get_course(self, brigade, index: int) -> dict | None:
        """
        Zwraca kurs dla danej brygady i indeksu (courseBrigadeIndex z traces).
        Indeks odpowiada pozycji na posortowanej wg czasu liście kursów w bloku.
        """
        brigade_str = str(brigade)
        block_id    = self.resolve_block_id(brigade_str)

        with self._lock:
            courses = self.blocks_cache.get(block_id)
            # Fallback: jeśli scalony block_id nie istnieje, próbuj oryginalnej brygady
            if not courses and block_id != brigade_str:
                log.debug(
                    "[%s] block_id '%s' nie w cache – próba oryginalnej brygady '%s'",
                    self.city_name, block_id, brigade_str,
                )
                courses  = self.blocks_cache.get(brigade_str)
                block_id = brigade_str if courses else block_id

        if not courses:
            log.debug("[%s] Brygada '%s' (block_id='%s') nie w cache",
                      self.city_name, brigade_str, block_id)
            return None
        if index >= len(courses):
            log.debug(
                "[%s] courseBrigadeIndex=%d poza zakresem dla block_id='%s' (len=%d)",
                self.city_name, index, block_id, len(courses),
            )
            return None
        return courses[index]


# ══════════════════════════════════════════════════════════════════════════════
#  GENERATOR GTFS-REALTIME
# ══════════════════════════════════════════════════════════════════════════════

def _haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6_371_000
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi       = math.radians(lat2 - lat1)
    dlambda    = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def _time_to_seconds(t: str) -> int:
    h, m, s = map(int, t.split(":"))
    return h * 3600 + m * 60 + s


def generate_realtime_feeds(city_cfg: dict, state: RealtimeState, output_dir: str) -> None:
    """
    Pobiera traces.json, buduje VehiclePositions + TripUpdates i zapisuje pliki
    .pb oraz .json do output_dir.
    """
    city_name  = city_cfg["name"]
    traces_url = city_cfg["cesip_traces_url"]

    # Pobranie traces
    try:
        r = requests.get(traces_url, timeout=10)
        r.raise_for_status()
        data = r.json()
        if not isinstance(data, dict):
            log.warning("[%s] traces.json – nieoczekiwany typ JSON", city_name)
            return
        traces = data.get("traces")
        if not isinstance(traces, list):
            log.warning("[%s] traces.json – brak pola 'traces'", city_name)
            return
    except Exception as exc:
        log.warning("[%s] Błąd pobierania traces.json: %s", city_name, exc)
        return

    log.info("[%s] traces count: %d", city_name, len(traces))

    now_ts = int(time.time())

    feed_vp = gtfs_realtime_pb2.FeedMessage()
    feed_tu = gtfs_realtime_pb2.FeedMessage()

    for feed in (feed_vp, feed_tu):
        feed.header.gtfs_realtime_version = "2.0"
        feed.header.incrementality        = gtfs_realtime_pb2.FeedHeader.FULL_DATASET
        feed.header.timestamp             = now_ts

    vp_json: dict = {"header": {"gtfs_realtime_version": "2.0", "timestamp": now_ts}, "entity": []}
    tu_json: list = []

    with state._lock:
        stops_snap      = state.stops
        stop_times_snap = state.stop_times

    for t in traces:
        brigade = t.get("brigade")
        index   = t.get("courseBrigadeIndex")
        trip_id = route_id = None

        if brigade is not None and index is not None:
            course = state.get_course(brigade, index)
            if course:
                trip_id  = course["trip_id"]
                route_id = course["route_id"]
                log.debug("[%s] trip_id=%s route_id=%s", city_name, trip_id, route_id)

        # ── VehiclePosition ───────────────────────────────────────────────
        e   = feed_vp.entity.add()
        e.id = f"VP_{t['vehicleNo']}"

        vp               = e.vehicle
        vp.vehicle.id    = str(t["vehicleNo"])
        vp.vehicle.label = str(t["vehicleNo"])
        if trip_id:
            vp.trip.trip_id = trip_id
        if route_id:
            vp.trip.route_id = route_id
        vp.position.latitude  = t["lat"]
        vp.position.longitude = t["lon"]
        vp.position.speed     = (t.get("speed") or 0) / 3.6
        vp.timestamp          = now_ts

        entity: dict = {
            "id":      str(t["vehicleNo"]),
            "vehicle": {
                "vehicle":  {"id": str(t["vehicleNo"]), "label": str(t["vehicleNo"])},
                "position": {"latitude": t["lat"], "longitude": t["lon"], "speed": t.get("speed") or 0},
                "timestamp": now_ts,
            },
        }
        if trip_id or route_id:
            entity["vehicle"]["trip"] = {}
            if trip_id:
                entity["vehicle"]["trip"]["trip_id"] = trip_id
            if route_id:
                entity["vehicle"]["trip"]["route_id"] = route_id
        vp_json["entity"].append(entity)

        if not trip_id:
            continue

        # ── TripUpdate ────────────────────────────────────────────────────
        stops_for_trip = stop_times_snap.get(str(trip_id))
        if not stops_for_trip:
            log.debug("[%s] Brak stop_times dla trip_id=%s", city_name, trip_id)
            continue

        next_stop  = stops_for_trip[0]
        stop_coords = stops_snap.get(next_stop["stop_id"])
        if stop_coords is None:
            continue
        stop_lat, stop_lon = stop_coords

        dist     = _haversine(t["lat"], t["lon"], stop_lat, stop_lon)
        now_dt   = datetime.now(tz=_WARSAW)
        now_sec  = now_dt.hour * 3600 + now_dt.minute * 60 + now_dt.second
        sched    = _hhmmss_to_secs(next_stop["arrival"])
        speed_ms = max((t.get("speed") or 10) / 3.6, 1)
        delay    = int(now_sec + dist / speed_ms - sched)

        log.debug("[%s] next_stop=%s dist=%dm delay=%ds", city_name, next_stop["stop_id"], int(dist), delay)

        e2    = feed_tu.entity.add()
        e2.id = f"TU_{trip_id}"

        tu              = e2.trip_update
        tu.trip.trip_id = trip_id
        tu.trip.route_id = route_id
        tu.timestamp    = now_ts

        stu               = tu.stop_time_update.add()
        stu.stop_id       = next_stop["stop_id"]
        stu.stop_sequence = next_stop["seq"]
        stu.arrival.delay   = delay
        stu.departure.delay = delay

        tu_json.append(trip_id)

    # Zapis plików
    os.makedirs(output_dir, exist_ok=True)
    for filename, content in (
        ("vehicle_positions.pb",   feed_vp.SerializeToString()),
        ("trip_updates.pb",        feed_tu.SerializeToString()),
        ("vehicle_positions.json", json.dumps(vp_json, indent=2, ensure_ascii=False).encode()),
        ("trip_updates.json",      json.dumps(tu_json, indent=2, ensure_ascii=False).encode()),
    ):
        with open(os.path.join(output_dir, filename), "wb") as fh:
            fh.write(content if isinstance(content, bytes) else content)

    log.info("[%s] GTFS-RT zapisane (%d pojazdów, %d trip_updates)", city_name, len(feed_vp.entity), len(feed_tu.entity))


def realtime_worker(city_cfg: dict, state: RealtimeState, output_dir: str) -> None:
    """Pętla w osobnym wątku: odświeża GTFS-RT co realtime_refresh_sec sekund."""
    city_name   = city_cfg["name"]
    interval    = city_cfg.get("realtime_refresh_sec", 10)
    log.info("[%s] Wątek GTFS-RT uruchomiony (interwał: %ds)", city_name, interval)
    while True:
        try:
            generate_realtime_feeds(city_cfg, state, output_dir)
        except Exception:
            log.exception("[%s] Błąd w pętli GTFS-RT", city_name)
        time.sleep(interval)


# ══════════════════════════════════════════════════════════════════════════════
#  OSRM – GENEROWANIE SHAPE'ÓW DLA RĘCZNYCH KURSÓW
# ══════════════════════════════════════════════════════════════════════════════

def _osrm_route(
    stops_lookup: dict[str, tuple[float, float]],
    ordered_stop_ids: list[str],
    osrm_url: str,
) -> list[tuple[float, float]]:
    """
    Odpytuje OSRM o trasę przechodzącą przez wszystkie przystanki (w kolejności).
    Zwraca listę punktów (lat, lon) tworzących shape.
    Jeśli OSRM niedostępny, zwraca linię prostą między przystankami.
    """
    # Budujemy ciąg współrzędnych dla OSRM: lon,lat;lon,lat;...
    coords_parts: list[str] = []
    for sid in ordered_stop_ids:
        pos = stops_lookup.get(sid)
        if pos is None:
            raise ValueError(f"Przystanek '{sid}' nie istnieje w stops (sprawdź EXTRA_STOPS i dane API)")
        lat, lon = pos
        coords_parts.append(f"{lon},{lat}")

    coords_str = ";".join(coords_parts)
    url = f"{osrm_url.rstrip('/')}/route/v1/driving/{coords_str}"
    params = {"overview": "full", "geometries": "geojson", "steps": "false"}

    try:
        resp = requests.get(url, params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        if data.get("code") == "Ok" and data.get("routes"):
            geometry = data["routes"][0]["geometry"]["coordinates"]
            # OSRM zwraca [lon, lat] → odwracamy na (lat, lon)
            return [(c[1], c[0]) for c in geometry]
        log.warning("OSRM zwrócił błąd dla shape: %s", data.get("message", "?"))
    except Exception as exc:
        log.warning("Błąd połączenia z OSRM (%s): %s – używam linii prostej", osrm_url, exc)

    # Fallback: linia prosta między wszystkimi przystankami
    points: list[tuple[float, float]] = []
    for sid in ordered_stop_ids:
        pos = stops_lookup[sid]
        if not points or points[-1] != pos:
            points.append(pos)
    return points


def _build_shapes_rows_for_manual(
    shape_id: str,
    shape_points: list[tuple[float, float]],
    existing_seq_offset: int = 0,
) -> list[dict]:
    """Przekształca listę (lat, lon) na wiersze shapes.txt z narastającym dystansem."""
    rows: list[dict] = []
    total_dist = 0.0
    EPSILON    = 1e-6  # km – minimalny przyrost (zapobiega duplikatom shape_dist_traveled)

    for i, (lat, lon) in enumerate(shape_points):
        if i > 0:
            prev_lat, prev_lon = shape_points[i - 1]
            R     = 6371.0
            dlat  = math.radians(lat - prev_lat)
            dlon  = math.radians(lon - prev_lon)
            a     = (math.sin(dlat / 2) ** 2
                     + math.cos(math.radians(prev_lat))
                     * math.cos(math.radians(lat))
                     * math.sin(dlon / 2) ** 2)
            dist  = 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))
            total_dist += max(dist, EPSILON)

        rows.append({
            "shape_id":            shape_id,
            "shape_pt_lat":        f"{lat:.6f}",
            "shape_pt_lon":        f"{lon:.6f}",
            "shape_pt_sequence":   existing_seq_offset + i,
            "shape_dist_traveled": f"{total_dist:.3f}",
        })
    return rows


# ══════════════════════════════════════════════════════════════════════════════
#  WSTRZYKIWANIE RĘCZNYCH KURSÓW DO ZIP
# ══════════════════════════════════════════════════════════════════════════════

def inject_manual_trips(zip_bytes: bytes, city_name: str) -> bytes:
    """
    Wstrzykuje EXTRA_STOPS i MANUAL_TRIPS do GTFS ZIP wygenerowanego przez
    generate_city().

    Kolejność operacji jest gwarantowana przez wywołującego (run_city):
      1. generate_city()       – pobiera dane z API, usuwa nieużywane przystanki
                                 (cleanup), zwraca sprzątniętyi ZIP.
      2. inject_manual_trips() – dopiero tutaj dodaje EXTRA_STOPS i MANUAL_TRIPS
                                 do już oczyszczonego ZIP.

    Dzięki temu EXTRA_STOPS i MANUAL_TRIPS nie są widoczne podczas cleanup'u
    w generate_city() i nie mogą zostać przypadkowo odfiltrowane ani
    zanieczyszczać statystyk used_stop_ids.

    Zwraca bajty zmodyfikowanego ZIP.
    """
    if not EXTRA_STOPS and not MANUAL_TRIPS:
        return zip_bytes  # nic do roboty

    # ── 1. Wczytaj wszystkie pliki z ZIP do słownika nazwa→tekst ─────────────
    file_contents: dict[str, str] = {}
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        for name in zf.namelist():
            with zf.open(name) as f:
                file_contents[name] = f.read().decode("utf-8")

    def _parse_csv(text: str) -> tuple[list[str], list[dict]]:
        """Zwraca (fieldnames, rows)."""
        reader = csv.DictReader(io.StringIO(text))
        rows   = list(reader)
        return list(reader.fieldnames or []), rows  # type: ignore[arg-type]

    # ── 2. Parsowanie plików potrzebnych do dalszej pracy ────────────────────
    stops_fields, stops_rows       = _parse_csv(file_contents["stops.txt"])
    trips_fields, trips_rows       = _parse_csv(file_contents["trips.txt"])
    st_fields,    st_rows          = _parse_csv(file_contents["stop_times.txt"])
    shapes_fields, shapes_rows     = _parse_csv(file_contents["shapes.txt"])
    _, cal_rows                    = _parse_csv(file_contents["calendar_dates.txt"])

    # Istniejące stop_id po cleanup'ie (tylko przystanki używane przez kursy z API)
    existing_stop_ids: set[str] = {r["stop_id"] for r in stops_rows}

    # Istniejące trip_id (żeby wykryć kolizje)
    existing_trip_ids: set[str] = {r["trip_id"] for r in trips_rows}

    # Mapa stop_id → (lat, lon) zbudowana z oczyszczonego stops.txt
    stops_lookup: dict[str, tuple[float, float]] = {
        r["stop_id"]: (float(r["stop_lat"]), float(r["stop_lon"]))
        for r in stops_rows
    }

    # Wszystkie service_id obecne w kalendarzu
    all_service_ids: set[str] = {r["service_id"] for r in cal_rows}

    log.info("[%s] inject_manual_trips: %d dodatkowych przystanków, %d ręcznych kursów",
             city_name, len(EXTRA_STOPS), len(MANUAL_TRIPS))

    # ── 3. EXTRA_STOPS → stops.txt ────────────────────────────────────────────
    # Dodajemy do już oczyszczonego stops.txt (po cleanup'ie z generate_city).
    added_stops = 0
    for es in EXTRA_STOPS:
        sid = str(es["stop_id"])
        if sid in existing_stop_ids:
            log.debug("[%s] Przystanek '%s' już istnieje – pomijam", city_name, sid)
            continue
        stops_rows.append({
            "stop_id":       sid,
            "stop_code":     str(es.get("stop_code", sid)),
            "stop_name":     es["stop_name"],
            "stop_lat":      str(es["stop_lat"]),
            "stop_lon":      str(es["stop_lon"]),
            "location_type": str(es.get("location_type", 0)),
        })
        stops_lookup[sid] = (float(es["stop_lat"]), float(es["stop_lon"]))
        existing_stop_ids.add(sid)
        added_stops += 1

    if added_stops:
        log.info("[%s] Dodano %d dodatkowych przystanków do stops.txt", city_name, added_stops)

    # ── 4. Shapes: ustal maksymalny istniejący numer sekwencji per shape_id ──
    # (potrzebne tylko jeśli w przyszłości shape_id już istnieje w shapes.txt;
    #  dla ręcznych kursów używamy prefiksu "M_" który nie koliduje z API)
    shape_seq_max: dict[str, int] = defaultdict(int)
    for sr in shapes_rows:
        sid = sr["shape_id"]
        seq = int(sr.get("shape_pt_sequence", 0))
        if seq > shape_seq_max[sid]:
            shape_seq_max[sid] = seq

    # Cache już wygenerowanych shape'ów (żeby nie odpytywać OSRM wielokrotnie
    # dla tego samego zestawu przystanków)
    _shape_cache: dict[str, list[tuple[float, float]]] = {}

    def _get_or_build_shape(stop_ids: list[str], shape_id: str) -> None:
        """Generuje shape przez OSRM (raz na unikalny shape_id) i dopisuje do shapes_rows."""
        if shape_id in _shape_cache:
            return
        log.info("[%s] Generowanie shape OSRM: %s (%d przystanków)", city_name, shape_id, len(stop_ids))
        pts = _osrm_route(stops_lookup, stop_ids, OSRM_URL)
        _shape_cache[shape_id] = pts
        new_rows = _build_shapes_rows_for_manual(shape_id, pts, existing_seq_offset=0)
        shapes_rows.extend(new_rows)
        log.info("[%s] Shape '%s': %d punktów", city_name, shape_id, len(new_rows))

    # ── 5. MANUAL_TRIPS → trips.txt + stop_times.txt + shapes.txt ────────────
    added_trips = 0
    skipped_trips = 0

    for mt in MANUAL_TRIPS:
        route_id     = str(mt["route_id"])
        block_id     = str(mt["block_id"])
        trip_headsign = mt.get("trip_headsign", "")
        direction_id  = str(mt.get("direction_id", ""))
        mt_service_ids: list[str] = [str(s) for s in mt.get("service_ids", [])]
        mt_stops: list[dict]      = mt["stops"]

        if len(mt_stops) < 2:
            log.warning("[%s] Ręczny kurs '%s' ma < 2 przystanki – pomijam", city_name, trip_headsign)
            skipped_trips += 1
            continue

        # Weryfikacja przystanków – stops_lookup zawiera już EXTRA_STOPS
        # dodane w kroku 3, więc referencje do nich są poprawnie rozwiązywane.
        stop_ids_ordered = [str(s["stop_id"]) for s in mt_stops]
        missing = [sid for sid in stop_ids_ordered if sid not in stops_lookup]
        if missing:
            log.warning(
                "[%s] Ręczny kurs '%s': brakujące stop_id %s – pomijam",
                city_name, trip_headsign, missing,
            )
            skipped_trips += 1
            continue

        # Shape_id oparty na liście przystanków (unikalny dla trasy, nie dla serwisu)
        shape_id = "M_" + "_".join(stop_ids_ordered)
        _get_or_build_shape(stop_ids_ordered, shape_id)

        for base_sid in mt_service_ids:
            # Sprawdź, czy w kalendarzu istnieje przynajmniej jeden wpis
            # pasujący do tego bazowego service_id (porównanie prefiksu)
            matching_service_ids = [
                cal_sid for cal_sid in all_service_ids
                if cal_sid == base_sid or cal_sid.startswith(base_sid + "-")
            ]
            if not matching_service_ids:
                log.warning(
                    "[%s] Ręczny kurs '%s': service_id '%s' nie znaleziony w calendar_dates – pomijam",
                    city_name, trip_headsign, base_sid,
                )
                skipped_trips += 1
                continue

            # Jeden trip per (kurs, service_id); używamy pierwszego pasującego
            # (w GTFS-Static jeden service_id = jeden typ dnia, daty są w calendar_dates)
            service_id_to_use = matching_service_ids[0]

            # Unikalne trip_id: prefiks "M", route, block, service, czas odjazdu
            dep_tag  = mt_stops[0]["departure_time"].replace(":", "")
            trip_id  = f"M_{route_id}_{block_id}_{service_id_to_use}_{dep_tag}"
            suffix   = 1
            base_tid = trip_id
            while trip_id in existing_trip_ids:
                trip_id = f"{base_tid}_{suffix}"
                suffix += 1
            existing_trip_ids.add(trip_id)

            # trips.txt
            trips_rows.append({
                "route_id":      route_id,
                "service_id":    service_id_to_use,
                "trip_id":       trip_id,
                "trip_headsign": trip_headsign,
                "direction_id":  direction_id,
                "shape_id":      shape_id,
                "block_id":      block_id,
            })

            # stop_times.txt
            for seq, stop_entry in enumerate(mt_stops):
                st_rows.append({
                    "trip_id":        trip_id,
                    "arrival_time":   stop_entry["departure_time"],
                    "departure_time": stop_entry["departure_time"],
                    "stop_id":        str(stop_entry["stop_id"]),
                    "stop_sequence":  seq,
                    "pickup_type":    str(stop_entry.get("pickup_type", 0)),
                    "drop_off_type":  str(stop_entry.get("drop_off_type", 0)),
                })

            added_trips += 1
            log.info(
                "[%s] Dodano ręczny kurs: trip_id='%s' route='%s' service='%s' headsign='%s'",
                city_name, trip_id, route_id, service_id_to_use, trip_headsign,
            )

    if skipped_trips:
        log.warning("[%s] Pominięto %d ręcznych kursów (patrz logi powyżej)", city_name, skipped_trips)

    log.info("[%s] inject_manual_trips: +%d kursów, +%d przystanków", city_name, added_trips, added_stops)

    # ── 6. Serializacja zmodyfikowanych plików i przepakowanie ZIP ────────────

    # Upewnij się, że shapes.txt ma kolumnę shape_dist_traveled
    shapes_out_fields = ["shape_id", "shape_pt_lat", "shape_pt_lon",
                         "shape_pt_sequence", "shape_dist_traveled"]

    # Istniejące wiersze shapes mogą nie mieć shape_dist_traveled – uzupełniamy ""
    for sr in shapes_rows:
        sr.setdefault("shape_dist_traveled", "")

    updated: dict[str, str] = {
        "stops.txt":      write_gtfs_csv(stops_rows,   stops_fields),
        "trips.txt":      write_gtfs_csv(trips_rows,   trips_fields),
        "stop_times.txt": write_gtfs_csv(st_rows,      st_fields),
        "shapes.txt":     write_gtfs_csv(shapes_rows,  shapes_out_fields),
    }
    file_contents.update(updated)

    # Złóż nowy ZIP
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, text in file_contents.items():
            zf.writestr(name, text)

    size = buf.tell()
    log.info("[%s] ZIP po wstrzyknięciu: %.1f MB", city_name, size / 1_048_576)
    return buf.getvalue()


# ══════════════════════════════════════════════════════════════════════════════
#  ŚCIEŻKI PLIKÓW
# ══════════════════════════════════════════════════════════════════════════════

def static_path(city_name: str) -> str:
    return os.path.join(OUTPUT_DIR, f"{city_name}.zip")


def rt_output_dir(city_name: str) -> str:
    return os.path.join(OUTPUT_DIR, f"rt_{city_name}")


# ══════════════════════════════════════════════════════════════════════════════
#  RUNNER – GENEROWANIE STATYCZNE + INICJALIZACJA REALTIME
# ══════════════════════════════════════════════════════════════════════════════

# Słownik: city_name → RealtimeState (wypełniony dla miast z realtime=True)
_rt_states: dict[str, RealtimeState] = {}
_rt_dirs_for_http: dict[str, str] = {}


async def run_city(city_cfg: dict) -> None:
    """
    Generuje GTFS-Static, wstrzykuje ręczne kursy, zapisuje ZIP, ładuje dane
    do RealtimeState.

    Kolejność kroków jest celowa i gwarantowana:
      1. generate_city()       – dane z API + cleanup nieużywanych przystanków
      2. inject_manual_trips() – DOPIERO TERAZ dodaje EXTRA_STOPS i MANUAL_TRIPS
                                 do oczyszczonego ZIP
      3. Zapis ZIP na dysk i załadowanie do RealtimeState
    """
    city_name = city_cfg["name"]
    try:
        # Krok 1: generowanie i cleanup (tylko dane z API)
        zip_bytes = await generate_city(city_cfg)

        # Krok 2: wstrzyknięcie ręcznych danych PO cleanup'ie.
        # Uruchamiamy w executor, żeby nie blokować pętli zdarzeń
        # podczas synchronicznych zapytań HTTP do OSRM.
        loop = asyncio.get_running_loop()
        zip_bytes = await loop.run_in_executor(None, inject_manual_trips, zip_bytes, city_name)

        # Krok 3: zapis i załadowanie do RealtimeState
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        path = static_path(city_name)
        with open(path, "wb") as fh:
            fh.write(zip_bytes)
        log.info("[%s] Static ZIP zapisany → %s", city_name, path)

        # Ładowanie do pamięci dla GTFS-RT (jeśli włączone).
        # load_from_zip buduje bloki bezpośrednio z ZIP – nie potrzeba zewnętrznego API.
        if city_cfg.get("realtime") and city_name in _rt_states:
            state = _rt_states[city_name]
            await loop.run_in_executor(None, state.load_from_zip, zip_bytes)

    except Exception:
        log.exception("[%s] Generowanie GTFS-Static nie powiodło się", city_name)


async def run_all() -> None:
    await asyncio.gather(*[run_city(cfg) for cfg in CITIES])


# ══════════════════════════════════════════════════════════════════════════════
#  SERWER HTTP – GTFS (Static+Realtime, aiohttp)
# ══════════════════════════════════════════════════════════════════════════════

async def handle_static_file(request: web.Request) -> web.Response:
    filename = request.match_info["filename"]
    # 1) pliki static: gtfs_output/<city>.zip
    static_path = os.path.join(OUTPUT_DIR, filename)
    if os.path.isfile(static_path):
        with open(static_path, "rb") as fh:
            data = fh.read()
        content_type = "application/zip" if filename.endswith(".zip") else "application/octet-stream"
        return web.Response(
            body=data,
            content_type=content_type,
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    # 2) pliki realtime: gtfs_output/rt_<city>/*.pb
    if filename in _ALLOWED_RT_FILES:
        rt_path = None
        for city_dir in _rt_dirs_for_http.values():
            candidate = os.path.join(city_dir, filename)
            if os.path.isfile(candidate):
                rt_path = candidate
                break

        if rt_path is None:
            raise web.HTTPServiceUnavailable(reason="Plik nie został jeszcze wygenerowany")

        with open(rt_path, "rb") as fh:
            data = fh.read()
        content_type = _ALLOWED_RT_FILES[filename]
        return web.Response(
            body=data,
            content_type=content_type,
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    raise web.HTTPNotFound(reason=f"Plik nie znaleziony: {filename}")


async def handle_static_index(request: web.Request) -> web.Response:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    base  = f"http://{HTTP_HOST}:{HTTP_PORT}{HTTP_PREFIX}"
    zip_files: list[str] = sorted([f for f in os.listdir(OUTPUT_DIR) if f.endswith(".zip")])

    pb_files_set: set[str] = set()
    for city_dir in _rt_dirs_for_http.values():
        try:
            for f in os.listdir(city_dir):
                if f.endswith(".pb"):
                    pb_files_set.add(f)
        except FileNotFoundError:
            # RT katalog może jeszcze nie istnieć (generowanie w tle)
            pass

    all_files = sorted(set(zip_files) | pb_files_set)
    lines = [
        "<html><body><h2>GTFS Feed Server</h2><ul>",
        *[f'<li><a href="{base}/{f}">{f}</a></li>' for f in all_files],
        "</ul></body></html>",
    ]
    return web.Response(text="\n".join(lines), content_type="text/html")


async def start_static_http_server() -> None:
    app = web.Application()
    app.router.add_get(HTTP_PREFIX,              handle_static_index)
    app.router.add_get(HTTP_PREFIX + "/",        handle_static_index)
    app.router.add_get(HTTP_PREFIX + "/{filename}", handle_static_file)

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, HTTP_HOST, HTTP_PORT)
    await site.start()

    log.info("Serwer GTFS (Static+Realtime): http://%s:%d%s/", HTTP_HOST, HTTP_PORT, HTTP_PREFIX)
    for cfg in CITIES:
        name = cfg["name"]
        log.info("  Static  : http://%s:%d%s/%s.zip", HTTP_HOST, HTTP_PORT, HTTP_PREFIX, name)

    for fname in sorted([k for k in _ALLOWED_RT_FILES.keys() if k.endswith(".pb")]):
        log.info("  RT PB    : http://%s:%d%s/%s", HTTP_HOST, HTTP_PORT, HTTP_PREFIX, fname)


# ══════════════════════════════════════════════════════════════════════════════
#  SERWER HTTP – GTFS-Realtime (synchroniczny BaseHTTPRequestHandler, port 8060)
# ══════════════════════════════════════════════════════════════════════════════

_ALLOWED_RT_FILES = {
    "vehicle_positions.pb":   "application/octet-stream",
    "trip_updates.pb":        "application/octet-stream",
    "vehicle_positions.json": "application/json",
    "trip_updates.json":      "application/json",
}


def _make_rt_handler(rt_dirs: dict[str, str]):
    """Fabryka handlera z zamkniętym rt_dirs (city_name → ścieżka katalogu)."""

    class RealtimeHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            prefix = RT_HTTP_PREFIX + "/"
            if not self.path.startswith(prefix):
                self.send_error(404, "Not Found")
                return

            rest  = self.path[len(prefix):].split("?")[0]
            parts = rest.split("/", 1)
            if len(parts) != 2:
                self.send_error(404, "Oczekiwano: /<city>/<filename>")
                return

            city_name, filename = parts
            if filename not in _ALLOWED_RT_FILES:
                self.send_error(404, f"Nieznany plik: {filename}")
                return

            city_dir = rt_dirs.get(city_name)
            if city_dir is None:
                self.send_error(404, f"Nieznane miasto: {city_name}")
                return

            filepath = os.path.join(city_dir, filename)
            if not os.path.isfile(filepath):
                self.send_error(503, "Plik nie został jeszcze wygenerowany")
                return

            content_type = _ALLOWED_RT_FILES[filename]
            with open(filepath, "rb") as f:
                data = f.read()

            self.send_response(200)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def log_message(self, fmt, *args):
            pass  # wyciszamy logi HTTP

    return RealtimeHandler


def start_realtime_http_server(rt_dirs: dict[str, str]) -> None:
    handler = _make_rt_handler(rt_dirs)
    server  = HTTPServer(("127.0.0.1", RT_HTTP_PORT), handler)
    log.info(
        "Serwer GTFS-RT   : http://127.0.0.1:%d%s/<miasto>/<plik>",
        RT_HTTP_PORT, RT_HTTP_PREFIX,
    )
    for city_name in rt_dirs:
        for fname in ("vehicle_positions.pb", "trip_updates.pb"):
            log.info(
                "  RT: http://127.0.0.1:%d%s/%s/%s",
                RT_HTTP_PORT, RT_HTTP_PREFIX, city_name, fname,
            )
    threading.Thread(target=server.serve_forever, daemon=True).start()


# ══════════════════════════════════════════════════════════════════════════════
#  GŁÓWNA PĘTLA
# ══════════════════════════════════════════════════════════════════════════════

async def run_loop() -> None:
    """
    Pełna pętla produkcyjna:
      1. Uruchom serwer HTTP GTFS-Static.
      2. Wygeneruj GTFS-Static dla wszystkich miast (pierwsze uruchomienie).
      3. Dla miast z realtime=True: uruchom wątek GTFS-RT (pliki .pb są udostępniane w tym samym serwerze HTTP).
      4. Codziennie o północy: ponownie generuj GTFS-Static; bloki są
         przebudowywane automatycznie z nowego ZIP wewnątrz load_from_zip.
    """
    # Inicjalizacja RealtimeState dla miast z realtime=True
    global _rt_states
    rt_dirs: dict[str, str] = {}
    for cfg in CITIES:
        if cfg.get("realtime"):
            city_name = cfg["name"]
            state     = RealtimeState(cfg)
            _rt_states[city_name]  = state
            rt_dirs[city_name]     = rt_output_dir(city_name)

    # Udostępniamy foldery RT do handlera HTTP (pliki .pb)
    global _rt_dirs_for_http
    _rt_dirs_for_http = rt_dirs

    # Serwery HTTP
    await start_static_http_server()

    # Pierwsze generowanie statyczne (ładuje też dane do RealtimeState)
    await run_all()

    # Uruchamiamy wątki GTFS-RT (startują po załadowaniu staticu)
    for cfg in CITIES:
        if cfg.get("realtime"):
            city_name = cfg["name"]
            state     = _rt_states[city_name]
            out_dir   = rt_dirs[city_name]
            t = threading.Thread(
                target=realtime_worker,
                args=(cfg, state, out_dir),
                daemon=True,
                name=f"rt-{city_name}",
            )
            t.start()
            log.info("[%s] Wątek GTFS-RT uruchomiony", city_name)

    # Codzienna pętla regeneracji statycznej o północy
    while True:
        now      = datetime.now(tz=_WARSAW)
        midnight = (now + timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0)
        wait_secs = (midnight - now).total_seconds()
        log.info(
            "Następna regeneracja GTFS-Static o północy (za %.0f s / %.1f h)",
            wait_secs, wait_secs / 3600,
        )
        await asyncio.sleep(wait_secs)

        # Regeneracja statyczna – load_from_zip wewnątrz run_city
        # automatycznie przebudowuje bloki z nowego ZIP.
        await run_all()


# ══════════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="GTFS-Static + GTFS-Realtime generator (przystanki.*)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Przykłady:\n"
            "  python gtfs_combined.py               # wszystkie miasta, pętla dzienna + serwery HTTP\n"
            "  python gtfs_combined.py bialystok     # jednorazowe generowanie static dla jednego miasta\n"
        ),
    )
    parser.add_argument(
        "city",
        nargs="?",
        help=(
            "Nazwa miasta do jednorazowego generowania GTFS-Static "
            "(bez serwera HTTP i bez pętli realtime). "
            "Pomiń, by uruchomić wszystkie miasta w trybie ciągłym."
        ),
    )
    args = parser.parse_args()

    if args.city:
        cfg = next((c for c in CITIES if c["name"] == args.city), None)
        if cfg is None:
            log.error("Nieznane miasto '%s'. Dostępne: %s",
                      args.city, ", ".join(c["name"] for c in CITIES))
            sys.exit(1)
        asyncio.run(run_city(cfg))
    else:
        try:
            asyncio.run(run_loop())
        except KeyboardInterrupt:
            log.info("Przerwano – zamykanie.")


if __name__ == "__main__":
    main()