#!/usr/bin/env python3
"""
GTFS-Static + GTFS-Realtime generator for Polish city transit APIs (format: przystanki.*)

Usage:
  python gtfs_generator.py              # Generate all cities, then repeat daily at midnight
  python gtfs_generator.py bialystok    # One-shot generation for a single city

Dependencies:
  pip install aiohttp gtfs-realtime-bindings
"""

import argparse
import asyncio
import csv
import io
import logging
import os
import sys
import zipfile
from collections import defaultdict
from datetime import datetime, timedelta
from typing import Any

import aiohttp
from aiohttp import web
from google.transit import gtfs_realtime_pb2


# ── CONFIGURATION ──────────────────────────────────────────────────────────────
#
# Add cities here.  Each entry supports the following top-level keys:
#
#   name            – short identifier used for CLI argument and output filename
#   base_url        – API base URL (no trailing slash)
#   realtime        – (bool) whether to also generate vehicle_positions.pb
#   agency          – fields for agency.txt  (see comments below)
#   feed_info       – static fields for feed_info.txt
#   route_colors    – (optional) list of colour rules for routes.txt
#   block_id_merges – (optional) list of brigade→block_id override rules
#
# ── agency fields ──────────────────────────────────────────────────────────────
#   Required: agency_id, agency_name, agency_url, agency_timezone
#   Optional: agency_lang, agency_phone, agency_fare_url, agency_email
#
# ── route_colors format ────────────────────────────────────────────────────────
#   A list of dicts, each with:
#     lines            – one of:
#                          "1"           single line name (string)
#                          ["2","3","4"] explicit list of line names
#                          "2-5"         inclusive numeric range (both ends included)
#     route_color      – 6-digit hex WITHOUT '#'  (e.g. "E2001A")
#     route_text_color – 6-digit hex WITHOUT '#'  (e.g. "FFFFFF")
#   Omit the key entirely to write routes.txt without colour columns.
#
# ── block_id_merges format ────────────────────────────────────────────────────
#   A list of dicts, each with:
#     service_id – stripped dayTypeSymbol (e.g. "P", "R", "S")
#     brigades   – list of brigade strings to merge (e.g. ["009-01", "126-01"])
#     block_id   – the single block_id to assign to all matching trips
#   Trips whose brigade is not listed anywhere keep their raw brigade as block_id.
#
# ──────────────────────────────────────────────────────────────────────────────

CITIES: list[dict] = [
    {
        "name": "bialystok",
        "base_url": "https://przystanki.bialystok.pl/portal",
        "realtime": True,   # ← set False to skip vehicle_positions.pb for this city
        "agency": {
            "agency_id":       "BKM",
            "agency_name":     "Zarząd Białostockiej Komunikacji Miejskiej",
            "agency_url":      "https://komunikacja.bialystok.pl",
            "agency_timezone": "Europe/Warsaw",
            "agency_lang":     "pl",
            "agency_phone":    "+48 85 869 69 69",
            "agency_fare_url": "https://komunikacja.bialystok.pl/",
            "agency_email":    "bkm@um.bialystok.pl",
        },
        "feed_info": {
            "feed_publisher_name": "Unofficial GTFS of Białostocka Komunikacja Miejska, generated by pawlinski07",
            "feed_publisher_url":  "https://github.com/pawlinski07/pawlinski-gtfs",
            "feed_lang":           "pl",
            "feed_timezone":       "Europe/Warsaw",
        },

        # ── Route colours (optional) ───────────────────────────────────────
        "route_colors": [
            {"lines": "1-6",   "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "8-9",   "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "11-21", "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "23-30", "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": "50",    "route_color": "6DB532", "route_text_color": "FFFFFF"},
            {"lines": ["7","10","22"],          "route_color": "225AC9", "route_text_color": "FFFFFF"},
            {"lines": ["200","201","202"],      "route_color": "BE080A", "route_text_color": "FFFFFF"},
            {"lines": "100-142",               "route_color": "225AC9", "route_text_color": "FFFFFF"},
            {"lines": ["N1","N2","N3","N4","N5","N6"], "route_color": "334455", "route_text_color": "FFFFFF"},
            {"lines": ["J1","J2","J3","J4","J5","J6"], "route_color": "FFF200", "route_text_color": "000000"},
        ],

        # ── Block-ID merges (optional) ─────────────────────────────────────
        "block_id_merges": [
            {
                "service_id": "P",
                "brigades":   ["009-01", "126-01"],
                "block_id":   "009-01+126-01",
            },
            {
                "service_id": "P",
                "brigades":   ["102-01", "122-01", "132-01"],
                "block_id":   "102-01+122-01+132-01",
            },
            {
                "service_id": "P",
                "brigades":   ["102-02", "122-02", "132-02"],
                "block_id":   "102-02+122-02+132-02",
            },
            {
                "service_id": "P",
                "brigades":   ["102-03", "122-03", "132-03"],
                "block_id":   "102-03+122-03+132-03",
            },
            {
                "service_id": "P",
                "brigades": ["111-02", "111-03"],
                "block_id": "111-02+111-03",
            },
            {
                "service_id": "R",
                "brigades":   ["102-01", "132-01", "132-02", "102-02"],
                "block_id":   "102-01+132-01+132-02+102-02",
            },
            {
                "service_id": "R",
                "brigades":   ["108-01", "108-02"],
                "block_id":   "108-01+108-02",
            },
            {
                "service_id": "R",
                "brigades":   ["111-01", "111-02", "111-03", "111-04"],
                "block_id":   "111-01+111-02+111-03+111-04",
            },
            {
                "service_id": "S",
                "brigades":   ["111-01", "111-02"],
                "block_id":   "111-01+111-02",
            },
            {
                "service_id": "S",
                "brigades":   ["108-01", "108-02"],
                "block_id":   "108-01+108-02",
            },
        ],
    },

    {
        "name": "szczytno",
        "base_url": "https://szczytno.tribus.pl",
        "realtime": True,
        "agency": {
            "agency_id":       "ZKM",
            "agency_name":     "Zakład Komunikacji Miejskiej Spółka z o.o.",
            "agency_url":      "https://zkm.szczytno.pl",
            "agency_timezone": "Europe/Warsaw",
            "agency_fare_url": "https://zkm.szczytno.pl/cennik",
            "agency_lang":     "pl",
        },
        "feed_info": {
            "feed_publisher_name": "Unofficial GTFS of ZKM Szczytno, generated by pawlinski07",
            "feed_publisher_url":  "https://github.com/pawlinski07/pawlinski-gtfs",
            "feed_lang":           "pl",
            "feed_timezone":       "Europe/Warsaw",
        },
        "route_colors": [
            {"lines": "1-3",   "route_color": "c00000", "route_text_color": "FFFFFF"},
        ],
        "block_id_merges": [],
    },

    # {
    #     "name": "elk",
    #     "base_url": "https://rozklady.miasto.elk.pl/",
    #     "realtime": True,
    #     "agency": {
    #         "agency_id":       "MZK",
    #         "agency_name":     "MZK Ełk",
    #         "agency_url":      "http://mzk.elk.pl/",
    #         "agency_timezone": "Europe/Warsaw",
    #         "agency_fare_url": "http://mzk.elk.pl/cennik.html",
    #         "agency_lang":     "pl",
    #     },
    #     "feed_info": {
    #         "feed_publisher_name": "Unofficial GTFS of MZK Ełk, generated by pawlinski07",
    #         "feed_publisher_url":  "https://github.com/pawlinski07/pawlinski-gtfs",
    #         "feed_lang":           "pl",
    #         "feed_timezone":       "Europe/Warsaw",
    #     },
    #     "route_colors": [
    #         {"lines": ["6","7","12","13","16"], "route_color": "008ED1", "route_text_color": "FFFFFF"},
    #         {"lines": "11", "route_color": "5F52A6", "route_text_color": "FFFFFF"},
    #         {"lines": "1", "route_color": "4CAF50", "route_text_color": "FFFFFF"},
    #         {"lines": "2", "route_color": "1B5E20", "route_text_color": "FFFFFF"},
    #         {"lines": ["3","14"], "route_color": "FFC107", "route_text_color": "FFFFFF"},
    #         {"lines": ["4","8","10"], "route_color": "FF9800", "route_text_color": "FFFFFF"},
    #         {"lines": "5", "route_color": "1D6C30", "route_text_color": "FFFFFF"},
    #         {"lines": "17", "route_color": "6E9E7C", "route_text_color": "FFFFFF"},
    #         {"lines": "18", "route_color": "556B2F", "route_text_color": "FFFFFF"},
    #     ],
    #     "block_id_merges": [],
    # },

    {
        "name": "tribus",
        "base_url": "https://ontime.tribus.pl/",
        "realtime": True,
        "agency": {
            "agency_id":       "TRiBUS",
            "agency_name":     "TRiBUS",
            "agency_url":      "https://rozklady.tribus.pl",
            "agency_timezone": "Europe/Warsaw",
            # "agency_fare_url": "http://mzk.elk.pl/cennik.html",
            "agency_lang":     "pl",
        },
        "feed_info": {
            "feed_publisher_name": "Unofficial GTFS of TRiBUS, generated by pawlinski07",
            "feed_publisher_url":  "https://github.com/pawlinski07/pawlinski-gtfs",
            "feed_lang":           "pl",
            "feed_timezone":       "Europe/Warsaw",
        },
        "route_colors": [
    {
        "lines": [
            "561","564","560","560S","566","S7","524","629","O2","O3",
            "302","309","512","578","701","703","597","549","595","D4",
            "D32","D33","D3","510","D1","S3","S1","S6","S5","573",
            "523","622","1","583","515","O5","633","304","305","585",
            "586","509","511","510E","562","563","567","568","567S","562S",
            "567bis","565","301","626B","626A","O4","601","473","428","623A",
            "623B","310","307","576","470","593","534","55","53","628",
            "308","51","52","478","303","569","58","579","581","590",
            "306","S4","577","D2","471","570","3","54","630","526",
            "631","638","704","702","25","627B","627A","632","O1","580",
            "311","472","574","572","600","O7","56","O6","571"
        ],
        "route_color": "D7EAE4",
        "route_text_color": "000000"
    }
],
        "block_id_merges": [],
    },
]

# Max simultaneous HTTP requests per city
CONCURRENCY: int = 15

# Seconds to wait between requests within a single concurrency slot (politeness)
REQUEST_DELAY: float = 0.05

# Retries on transient failures
MAX_RETRIES: int = 3

# Directory where output ZIPs and PBs are written
OUTPUT_DIR: str = "gtfs_output"

# How often (seconds) to refresh vehicle positions for realtime cities
REALTIME_REFRESH_SEC: int = 15

# HTTP server bind address and port
HTTP_HOST: str = "127.0.0.1"
HTTP_PORT: int = 8050
# URL prefix under which files are served
HTTP_PREFIX: str = "/ontimegtfs"

# GTFS route_type mapping
ROUTE_TYPE_MAP: dict[str, int] = {
    "BUS":   3,
    "TRAM":  0,
    "METRO": 1,
    "TRAIN": 2,
    "FERRY": 4,
}

# ── LOGGING ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ── UTILITY FUNCTIONS ─────────────────────────────────────────────────────────

def secs_to_hhmmss(secs: int) -> str:
    """Convert seconds-since-midnight to HH:MM:SS.
    Values >86400 are valid in GTFS (past-midnight trips)."""
    h = secs // 3600
    m = (secs % 3600) // 60
    s = secs % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def ms_to_date_str(ms: int) -> str:
    """Convert a UTC millisecond timestamp to GTFS date string YYYYMMDD."""
    return datetime.utcfromtimestamp(ms / 1000).strftime("%Y%m%d")


def strip_today_suffix(symbol: str) -> str:
    """Strip the '_T' (today) suffix from a dayTypeSymbol."""
    idx = symbol.find("_T")
    return symbol[:idx] if idx != -1 else symbol


def write_gtfs_csv(rows: list[dict], fieldnames: list[str]) -> str:
    """Serialise a list of dicts to a GTFS-compliant CSV string (CRLF line endings)."""
    buf = io.StringIO()
    writer = csv.DictWriter(
        buf,
        fieldnames=fieldnames,
        lineterminator="\r\n",
        extrasaction="ignore",
    )
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def build_route_color_lookup(route_colors_cfg: list[dict]) -> dict[str, tuple[str, str]]:
    """Parse the route_colors config into a dict: line_name → (route_color, route_text_color)."""
    lookup: dict[str, tuple[str, str]] = {}
    for rule in route_colors_cfg:
        color      = rule["route_color"]
        text_color = rule["route_text_color"]
        spec       = rule["lines"]

        if isinstance(spec, list):
            names = [str(n) for n in spec]
        elif isinstance(spec, str) and "-" in spec:
            parts = spec.split("-", 1)
            if parts[0].isdigit() and parts[1].isdigit():
                lo, hi = int(parts[0]), int(parts[1])
                names  = [str(i) for i in range(lo, hi + 1)]
            else:
                names = [spec]
        else:
            names = [str(spec)]

        for name in names:
            lookup[name] = (color, text_color)

    return lookup


def build_block_id_lookup(
    block_id_merges: list[dict],
) -> dict[tuple[str, str], str]:
    """Build a lookup: (service_id, brigade) -> block_id from block_id_merges config."""
    lookup: dict[tuple[str, str], str] = {}
    for rule in block_id_merges:
        sid      = rule["service_id"]
        block_id = rule["block_id"]
        for brigade in rule["brigades"]:
            lookup[(sid, brigade)] = block_id
    return lookup


# ── HTTP CLIENT ───────────────────────────────────────────────────────────────

class APIClient:
    """Async HTTP client for the przystanki.* API with rate limiting and retries."""

    def __init__(
        self,
        base_url: str,
        session: aiohttp.ClientSession,
        semaphore: asyncio.Semaphore,
    ) -> None:
        self.base = base_url.rstrip("/")
        self.session = session
        self.sem = semaphore

    async def get(self, path: str, params: dict | None = None) -> Any | None:
        url = f"{self.base}/{path}"
        async with self.sem:
            await asyncio.sleep(REQUEST_DELAY)
            for attempt in range(MAX_RETRIES):
                try:
                    async with self.session.get(
                        url,
                        params=params,
                        timeout=aiohttp.ClientTimeout(total=30),
                    ) as resp:
                        resp.raise_for_status()
                        return await resp.json(content_type=None)
                except Exception as exc:
                    if attempt == MAX_RETRIES - 1:
                        log.warning(
                            "Request failed after %d attempts: %s %s - %s",
                            MAX_RETRIES, url, params, exc,
                        )
                        return None
                    await asyncio.sleep(2 ** attempt)
        return None


# ── VEHICLE POSITIONS (GTFS-RT) ───────────────────────────────────────────────

async def fetch_vehicle_positions(city_cfg: dict) -> bytes | None:
    """
    Fetch running vehicles from getRunningVehicles.json and build a GTFS-RT
    VehiclePositions FeedMessage, returned as serialised protobuf bytes.

    The API field ``courseLoid`` maps directly to GTFS ``trip_id``.
    """
    city_name = city_cfg["name"]
    base_url  = city_cfg["base_url"]

    sem = asyncio.Semaphore(CONCURRENCY)
    connector = aiohttp.TCPConnector(limit=CONCURRENCY)

    async with aiohttp.ClientSession(connector=connector) as session:
        api = APIClient(base_url, session, sem)
        data = await api.get("getRunningVehicles.json")

    if data is None:
        log.warning("[%s] getRunningVehicles.json returned no data", city_name)
        return None

    if data.get("offline"):
        log.info("[%s] Realtime feed reports offline – skipping vehicle positions", city_name)
        return None

    vehicles = data.get("vehicles") or []

    feed = gtfs_realtime_pb2.FeedMessage()
    feed.header.gtfs_realtime_version = "2.0"
    feed.header.incrementality = gtfs_realtime_pb2.FeedHeader.FULL_DATASET
    feed.header.timestamp = int(datetime.utcnow().timestamp())

    for v in vehicles:
        lat  = v.get("latitude")
        lon  = v.get("longitude")
        if lat is None or lon is None:
            continue  # position required

        entity = feed.entity.add()
        entity.id = str(v.get("vehicleId", v.get("courseLoid", "")))

        # Trip descriptor – courseLoid is the GTFS trip_id
        course_id = v.get("courseLoid")
        if course_id is not None:
            entity.vehicle.trip.trip_id = str(course_id)

        route_name = v.get("lineName")
        if route_name:
            entity.vehicle.trip.route_id = str(route_name)

        # Vehicle descriptor
        vehicle_id = v.get("vehicleId")
        if vehicle_id:
            entity.vehicle.vehicle.id    = str(vehicle_id)
            entity.vehicle.vehicle.label = str(vehicle_id)

        # Position
        entity.vehicle.position.latitude  = float(lat)
        entity.vehicle.position.longitude = float(lon)

        angle = v.get("angle")
        if angle is not None:
            entity.vehicle.position.bearing = float(angle)

        # Current stop / status
        on_stop = v.get("onStopPoint")
        if on_stop:
            entity.vehicle.stop_id    = str(on_stop)
            entity.vehicle.current_status = (
                gtfs_realtime_pb2.VehiclePosition.STOPPED_AT
            )
        else:
            nearest = v.get("nearestSymbol")
            if nearest:
                entity.vehicle.stop_id = str(nearest)
            entity.vehicle.current_status = (
                gtfs_realtime_pb2.VehiclePosition.IN_TRANSIT_TO
            )

        order = v.get("orderInCourse")
        if order is not None:
            entity.vehicle.current_stop_sequence = int(order)

        # Timestamp from lastPingDate (ms → s)
        ping_ms = v.get("lastPingDate")
        if ping_ms:
            entity.vehicle.timestamp = int(ping_ms // 1000)

        # Congestion / occupancy fields left at defaults (unknown)

    log.info(
        "[%s] Built vehicle positions feed: %d vehicles",
        city_name, len(feed.entity),
    )
    return feed.SerializeToString()


# ── GTFS STATIC GENERATOR ─────────────────────────────────────────────────────

async def generate_city(city_cfg: dict) -> bytes:
    """Fetch all API data for one city and return a GTFS ZIP as bytes."""

    city_name  = city_cfg["name"]
    base_url   = city_cfg["base_url"]
    agency_cfg = city_cfg["agency"]
    feed_cfg   = city_cfg["feed_info"]

    route_color_lookup = build_route_color_lookup(city_cfg.get("route_colors") or [])
    block_id_lookup    = build_block_id_lookup(city_cfg.get("block_id_merges") or [])
    use_route_colors   = bool(route_color_lookup)

    now          = datetime.now()
    feed_start   = now.strftime("%Y%m%d")
    feed_end     = (now + timedelta(days=90)).strftime("%Y%m%d")
    feed_version = now.strftime("%Y%m%d%H%M")

    log.info("[%s] Starting GTFS generation ...", city_name)

    sem       = asyncio.Semaphore(CONCURRENCY)
    connector = aiohttp.TCPConnector(limit=CONCURRENCY)

    async with aiohttp.ClientSession(connector=connector) as session:
        api = APIClient(base_url, session, sem)

        # 1. Fetch base resources in parallel
        log.info("[%s] Fetching base data (stops, lines, calendar, variant names, main variants) ...", city_name)
        stops_data, lines_data, calendar_data, variant_names_raw, main_variants_raw = await asyncio.gather(
            api.get("getStops.json"),
            api.get("getLines.json"),
            api.get("getCalendar.json"),
            api.get("getMappedVariantNames.json"),
            api.get("getMainVariantsByLineName.json"),
        )

        stops         = stops_data["stopPoints"]
        lines         = lines_data["lines"]
        calendar_days = calendar_data["days"]
        variant_names = variant_names_raw or {}

        # Build variant_id → direction_id lookup from main variants.
        # Response format: {"lineName": [null, variantId_dir0, variantId_dir1], ...}
        # Index 1 → direction_id 0 ("jazda"), index 2 → direction_id 1 ("powrót").
        variant_direction: dict[int, int] = {}
        for _line, variants in (main_variants_raw or {}).items():
            if isinstance(variants, list):
                if len(variants) > 1 and variants[1] is not None:
                    variant_direction[int(variants[1])] = 0
                if len(variants) > 2 and variants[2] is not None:
                    variant_direction[int(variants[2])] = 1

        log.info("[%s] direction_id lookup: %d variants mapped", city_name, len(variant_direction))

        symbol_to_stop:  dict[str, dict] = {s["symbol"]: s for s in stops}
        line_name_to_id: dict[str, int]  = {l["name"]: l["name"] for l in lines}

        log.info("[%s] %d stops, %d lines, %d calendar days",
                 city_name, len(stops), len(lines), len(calendar_days))

        # 2. Process calendar -> service_id mapping
        service_dates: dict[str, list[str]]    = defaultdict(list)
        service_representative: dict[str, int] = {}

        for day in calendar_days:
            raw_sym    = day["dayType"]["dayTypeSymbol"]
            service_id = strip_today_suffix(raw_sym)
            date_str   = ms_to_date_str(day["date"])
            service_dates[service_id].append(date_str)
            if "_T" not in raw_sym and service_id not in service_representative:
                service_representative[service_id] = day["date"]

        for day in calendar_days:
            raw_sym    = day["dayType"]["dayTypeSymbol"]
            service_id = strip_today_suffix(raw_sym)
            if service_id not in service_representative:
                service_representative[service_id] = day["date"]

        log.info("[%s] %d service types: %s",
                 city_name, len(service_representative),
                 list(service_representative.keys()))

        # 3. Fetch atomic schedules
        total_calls = len(stops) * len(service_representative)
        log.info(
            "[%s] Fetching atomic schedules (%d stops x %d service types = %d calls) ...",
            city_name, len(stops), len(service_representative), total_calls,
        )

        async def fetch_atomic(stop_symbol: str, date_ms: int, service_id: str):
            data = await api.get(
                "getAtomicSchedule.json",
                {"symbol": stop_symbol, "date": date_ms},
            )
            return stop_symbol, service_id, data

        atomic_tasks = [
            fetch_atomic(s["symbol"], date_ms, sid)
            for sid, date_ms in service_representative.items()
            for s in stops
        ]

        trips_meta: dict[int, dict]     = {}
        seen_orders: dict[int, set]     = defaultdict(set)
        stop_times_raw: dict[int, list] = defaultdict(list)

        completed      = 0
        atomic_results = await asyncio.gather(*atomic_tasks, return_exceptions=True)

        for result in atomic_results:
            completed += 1
            if completed % 500 == 0 or completed == total_calls:
                log.info("[%s] Processed %d / %d atomic schedule responses",
                         city_name, completed, total_calls)

            if isinstance(result, Exception) or result is None:
                continue

            stop_symbol, service_id, data = result
            if data is None or "lineSchedules" not in data:
                continue

            stop = symbol_to_stop.get(stop_symbol)
            if stop is None:
                continue

            stop_id     = stop["id"]
            on_request  = bool(stop.get("onRequest"))
            getting_out = bool(stop.get("gettingOut"))

            if on_request:
                pickup_type, dropoff_type = 3, 3
            elif getting_out:
                pickup_type, dropoff_type = 1, 0
            else:
                pickup_type, dropoff_type = 0, 0

            for line_name, line_sched in data["lineSchedules"].items():
                route_id = line_name_to_id.get(line_name, line_name)

                for dep in line_sched["departures"]:
                    course_id  = dep["courseId"]
                    order      = dep["orderInCourse"]
                    variant_id = dep["variantId"]
                    brigade    = dep.get("brigade") or ""

                    if course_id not in trips_meta:
                        headsign = (
                            dep.get("optionalDirection")
                            or variant_names.get(str(variant_id), "")
                        )
                        trips_meta[course_id] = {
                            "trip_id":       course_id,
                            "route_id":      route_id,
                            "service_id":    service_id,
                            "shape_id":      variant_id,
                            "trip_headsign": headsign,
                            "variant_id":    variant_id,
                            "brigade":       brigade,
                        }

                    if order not in seen_orders[course_id]:
                        seen_orders[course_id].add(order)
                        stop_times_raw[course_id].append((
                            order,
                            stop_id,
                            dep["scheduledDepartureSec"],
                            pickup_type,
                            dropoff_type,
                        ))

        log.info(
            "[%s] Collected %d trips, %d stop-time entries",
            city_name, len(trips_meta),
            sum(len(v) for v in stop_times_raw.values()),
        )

        # 4. Fetch shapes + variant headsigns (optionalName) from getTheoreticalCourseDetails.json
        variant_ids = sorted({t["variant_id"] for t in trips_meta.values()})
        log.info("[%s] Fetching %d variant shapes ...", city_name, len(variant_ids))

        shape_tasks = [
            api.get("getTheoreticalCourseDetails.json", {"variantId": vid})
            for vid in variant_ids
        ]
        shape_results = await asyncio.gather(*shape_tasks, return_exceptions=True)

        shapes: dict[int, list[tuple[float, float]]] = {}
        # variantId → optionalName from getTheoreticalCourseDetails; used as headsign fallback
        variant_headsign: dict[int, str] = {}

        for vid, res in zip(variant_ids, shape_results):
            if isinstance(res, Exception) or res is None:
                continue
            if "segments" not in res:
                continue

            # Capture headsign from optionalName (more authoritative than getMappedVariantNames)
            optional_name = res.get("optionalName") or ""
            if optional_name:
                variant_headsign[vid] = optional_name

            points: list[tuple[float, float]] = []
            for seg in res["segments"]:
                nodes     = sorted(seg["nodes"], key=lambda n: n["orderNo"])
                start_idx = 1 if points else 0
                for node in nodes[start_idx:]:
                    points.append((node["latitude"], node["longitude"]))

            if points:
                shapes[vid] = points

        log.info("[%s] Collected shapes for %d / %d variants; %d variant headsigns",
                 city_name, len(shapes), len(variant_ids), len(variant_headsign))

        # 4b. Back-fill trip_headsign from variant_headsign where still empty,
        #     and attach direction_id (resolved via variant_direction lookup).
        for trip in trips_meta.values():
            vid = trip["variant_id"]
            # Headsign: prefer existing value, then optionalName from variant details
            if not trip["trip_headsign"]:
                trip["trip_headsign"] = variant_headsign.get(vid, "")
            # direction_id: 0 or 1 if found, else "" (written as empty string in CSV)
            trip["direction_id"] = variant_direction.get(vid, "")

    # 5. Build GTFS CSV files

    # agency.txt
    agency_fields_ordered = [
        "agency_id", "agency_name", "agency_url", "agency_timezone",
        "agency_lang", "agency_phone", "agency_fare_url", "agency_email",
    ]
    agency_present = [f for f in agency_fields_ordered if f in agency_cfg]
    agency_csv = write_gtfs_csv([agency_cfg], agency_present)

    # stops.txt – only keep stops that appear in at least one stop_time entry
    used_stop_ids: set = {
        entry[1]          # index 1 = stop_id in the (order, stop_id, dep_secs, ...) tuple
        for entries in stop_times_raw.values()
        for entry in entries
    }
    stops_rows = [
        {
            "stop_id":       s["id"],
            "stop_code":     s["symbol"],
            "stop_name":     s["name"],
            "stop_lat":      s["latitude"],
            "stop_lon":      s["longitude"],
            "location_type": 0,
        }
        for s in stops
        if s["id"] in used_stop_ids
    ]
    removed_stops = len(stops) - len(stops_rows)
    if removed_stops:
        log.info(
            "[%s] Cleaned stops.txt: removed %d stop(s) with no stop_times entries",
            city_name, removed_stops,
        )
    stops_csv = write_gtfs_csv(
        stops_rows,
        ["stop_id", "stop_code", "stop_name", "stop_lat", "stop_lon", "location_type"],
    )

    # routes.txt
    route_fields = [
        "route_id", "agency_id", "route_short_name", "route_long_name", "route_type",
    ]
    if use_route_colors:
        route_fields += ["route_color", "route_text_color"]

    seen_route_ids: set = set()
    routes_rows = []
    for line in lines:
        if line["id"] in seen_route_ids:
            continue
        seen_route_ids.add(line["id"])
        row: dict = {
            "route_id":         line["name"],
            "agency_id":        agency_cfg["agency_id"],
            "route_short_name": line["name"],
            "route_long_name":  "",
            "route_type":       ROUTE_TYPE_MAP.get(line.get("lineType", "BUS"), 3),
        }
        if use_route_colors:
            color_pair = route_color_lookup.get(line["name"])
            row["route_color"]      = color_pair[0] if color_pair else ""
            row["route_text_color"] = color_pair[1] if color_pair else ""
        routes_rows.append(row)
    routes_csv = write_gtfs_csv(routes_rows, route_fields)

    # calendar_dates.txt
    cal_rows = [
        {"service_id": service_id, "date": date_str, "exception_type": 1}
        for service_id, dates in service_dates.items()
        for date_str in dates
    ]
    cal_rows.sort(key=lambda r: (r["date"], r["service_id"]))
    cal_csv = write_gtfs_csv(cal_rows, ["service_id", "date", "exception_type"])

    # trips.txt
    trips_rows = []
    for t in trips_meta.values():
        brigade    = t["brigade"]
        service_id = t["service_id"]
        if brigade:
            block_id = block_id_lookup.get((service_id, brigade), brigade)
        else:
            block_id = ""
        trips_rows.append({
            "route_id":      t["route_id"],
            "service_id":    service_id,
            "trip_id":       t["trip_id"],
            "trip_headsign": t["trip_headsign"],
            "direction_id":  t.get("direction_id", ""),
            "shape_id":      t["shape_id"],
            "block_id":      block_id,
        })
    trips_csv = write_gtfs_csv(
        trips_rows,
        ["route_id", "service_id", "trip_id", "trip_headsign", "direction_id", "shape_id", "block_id"],
    )

    # stop_times.txt
    # The API returns scheduledDepartureSec as seconds-since-midnight and resets
    # to 0 after midnight instead of continuing past 86400.  We detect the
    # wrap-around within each trip's sorted sequence and apply a cumulative
    # +86400 offset so that GTFS times are strictly non-decreasing per trip.
    _DAY = 86400
    st_rows = []
    for course_id, entries in stop_times_raw.items():
        sorted_entries = sorted(entries)          # sort by order (first element)
        offset   = 0
        prev_raw = None
        for order, stop_id, dep_secs, pickup_type, dropoff_type in sorted_entries:
            if prev_raw is not None and dep_secs < prev_raw:
                # Time went backwards → trip crossed midnight
                offset += _DAY
            prev_raw = dep_secs
            time_str = secs_to_hhmmss(dep_secs + offset)
            st_rows.append({
                "trip_id":        course_id,
                "arrival_time":   time_str,
                "departure_time": time_str,
                "stop_id":        stop_id,
                "stop_sequence":  order,
                "pickup_type":    pickup_type,
                "drop_off_type":  dropoff_type,
            })
    st_rows.sort(key=lambda r: (r["trip_id"], r["stop_sequence"]))
    st_csv = write_gtfs_csv(
        st_rows,
        ["trip_id", "arrival_time", "departure_time",
         "stop_id", "stop_sequence", "pickup_type", "drop_off_type"],
    )

    # shapes.txt
    shapes_rows = [
        {
            "shape_id":          shape_id,
            "shape_pt_lat":      lat,
            "shape_pt_lon":      lon,
            "shape_pt_sequence": seq,
        }
        for shape_id, points in shapes.items()
        for seq, (lat, lon) in enumerate(points)
    ]
    shapes_csv = write_gtfs_csv(
        shapes_rows,
        ["shape_id", "shape_pt_lat", "shape_pt_lon", "shape_pt_sequence"],
    )

    # feed_info.txt
    feed_row = {
        "feed_publisher_name": feed_cfg["feed_publisher_name"],
        "feed_publisher_url":  feed_cfg["feed_publisher_url"],
        "feed_lang":           feed_cfg.get("feed_lang", "pl"),
        "feed_timezone":       feed_cfg.get("feed_timezone", "Europe/Warsaw"),
        "feed_start_date":     feed_start,
        "feed_end_date":       feed_end,
        "feed_version":        feed_version,
    }
    feed_csv = write_gtfs_csv([feed_row], list(feed_row.keys()))

    # 6. Pack into ZIP
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("agency.txt",         agency_csv)
        zf.writestr("stops.txt",          stops_csv)
        zf.writestr("routes.txt",         routes_csv)
        zf.writestr("calendar_dates.txt", cal_csv)
        zf.writestr("trips.txt",          trips_csv)
        zf.writestr("stop_times.txt",     st_csv)
        zf.writestr("shapes.txt",         shapes_csv)
        zf.writestr("feed_info.txt",      feed_csv)

    size = buf.tell()
    log.info("[%s] Generation complete - ZIP size: %s bytes (%.1f MB)",
             city_name, f"{size:,}", size / 1_048_576)
    return buf.getvalue()


# ── FILE HELPERS ──────────────────────────────────────────────────────────────

def static_path(city_name: str) -> str:
    return os.path.join(OUTPUT_DIR, f"{city_name}.zip")


def realtime_path(city_name: str) -> str:
    return os.path.join(OUTPUT_DIR, f"{city_name}.pb")


# ── RUNNER HELPERS ────────────────────────────────────────────────────────────

async def run_city(city_cfg: dict) -> None:
    """Generate GTFS static for one city and write the ZIP to OUTPUT_DIR."""
    city_name = city_cfg["name"]
    try:
        data = await generate_city(city_cfg)
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        path = static_path(city_name)
        with open(path, "wb") as fh:
            fh.write(data)
        log.info("[%s] Static saved -> %s", city_name, path)
    except Exception:
        log.exception("[%s] Static generation failed", city_name)


async def run_realtime_once(city_cfg: dict) -> None:
    """Fetch and save vehicle positions for one city."""
    city_name = city_cfg["name"]
    try:
        pb_bytes = await fetch_vehicle_positions(city_cfg)
        if pb_bytes is not None:
            os.makedirs(OUTPUT_DIR, exist_ok=True)
            path = realtime_path(city_name)
            with open(path, "wb") as fh:
                fh.write(pb_bytes)
            log.debug("[%s] Realtime saved -> %s (%d bytes)", city_name, path, len(pb_bytes))
    except Exception:
        log.exception("[%s] Realtime update failed", city_name)


async def realtime_loop(city_cfg: dict) -> None:
    """Continuously refresh vehicle positions every REALTIME_REFRESH_SEC seconds."""
    city_name = city_cfg["name"]
    log.info("[%s] Starting realtime loop (every %ds)", city_name, REALTIME_REFRESH_SEC)
    while True:
        await run_realtime_once(city_cfg)
        await asyncio.sleep(REALTIME_REFRESH_SEC)


async def run_all() -> None:
    """Generate GTFS static for every city in CITIES concurrently."""
    await asyncio.gather(*[run_city(cfg) for cfg in CITIES])


# ── HTTP SERVER ───────────────────────────────────────────────────────────────

async def handle_file(request: web.Request) -> web.Response:
    """Serve a file from OUTPUT_DIR based on the URL path."""
    filename = request.match_info["filename"]
    filepath = os.path.join(OUTPUT_DIR, filename)

    if not os.path.isfile(filepath):
        raise web.HTTPNotFound(reason=f"File not found: {filename}")

    # Choose content type
    if filename.endswith(".zip"):
        content_type = "application/zip"
    elif filename.endswith(".pb"):
        content_type = "application/octet-stream"
    else:
        content_type = "application/octet-stream"

    with open(filepath, "rb") as fh:
        data = fh.read()

    return web.Response(
        body=data,
        content_type=content_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


async def handle_index(request: web.Request) -> web.Response:
    """Simple index page listing all available files."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    files = sorted(os.listdir(OUTPUT_DIR))
    base  = f"http://{HTTP_HOST}:{HTTP_PORT}{HTTP_PREFIX}"
    lines = [
        "<html><body><h2>GTFS Feed Server</h2><ul>",
        *[f'<li><a href="{base}/{f}">{f}</a></li>' for f in files if f.endswith((".zip", ".pb"))],
        "</ul></body></html>",
    ]
    return web.Response(text="\n".join(lines), content_type="text/html")


async def start_http_server() -> None:
    """Start the aiohttp web server."""
    app = web.Application()
    app.router.add_get(HTTP_PREFIX, handle_index)
    app.router.add_get(HTTP_PREFIX + "/", handle_index)
    app.router.add_get(HTTP_PREFIX + "/{filename}", handle_file)

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, HTTP_HOST, HTTP_PORT)
    await site.start()
    log.info(
        "HTTP server started: http://%s:%d%s/",
        HTTP_HOST, HTTP_PORT, HTTP_PREFIX,
    )
    # URLs for each city
    for cfg in CITIES:
        name = cfg["name"]
        log.info(
            "  Static  : http://%s:%d%s/%s.zip",
            HTTP_HOST, HTTP_PORT, HTTP_PREFIX, name,
        )
        if cfg.get("realtime"):
            log.info(
                "  Realtime: http://%s:%d%s/%s.pb",
                HTTP_HOST, HTTP_PORT, HTTP_PREFIX, name,
            )


async def run_loop() -> None:
    """
    Full production loop:
      1. Start HTTP server.
      2. Generate static GTFS for all cities immediately.
      3. Start per-city realtime loops (if enabled).
      4. Regenerate static GTFS every day at midnight.
    """
    await start_http_server()

    # Initial static generation
    await run_all()

    # Launch realtime refresh tasks for cities that have it enabled
    for cfg in CITIES:
        if cfg.get("realtime"):
            asyncio.create_task(realtime_loop(cfg))

    # Daily static re-generation loop
    while True:
        now      = datetime.now()
        midnight = (now + timedelta(days=1)).replace(
            hour=0, minute=0, second=0, microsecond=0,
        )
        wait_secs = (midnight - now).total_seconds()
        log.info(
            "Next static regeneration at midnight (in %.0f s / %.1f h)",
            wait_secs, wait_secs / 3600,
        )
        await asyncio.sleep(wait_secs)
        await run_all()


# ── ENTRY POINT ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="GTFS-Static + GTFS-Realtime generator for Polish city transit APIs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python gtfs_generator.py               # all cities, loop daily + HTTP server\n"
            "  python gtfs_generator.py bialystok     # one-shot static for one city\n"
        ),
    )
    parser.add_argument(
        "city",
        nargs="?",
        help=(
            "City name for one-shot static generation (no HTTP server, no realtime loop). "
            "Omit to run all cities on a daily loop with HTTP server and realtime feeds."
        ),
    )
    args = parser.parse_args()

    city_names = [c["name"] for c in CITIES]

    if args.city:
        # One-shot: generate static only for the requested city
        cfg = next((c for c in CITIES if c["name"] == args.city), None)
        if cfg is None:
            log.error(
                "Unknown city '%s'. Available: %s",
                args.city, ", ".join(city_names),
            )
            sys.exit(1)
        asyncio.run(run_city(cfg))
    else:
        try:
            asyncio.run(run_loop())
        except KeyboardInterrupt:
            log.info("Interrupted - exiting.")


if __name__ == "__main__":
    main()